'use strict';
const $ = id => document.getElementById(id);
const state = { csrf:'', catalog:[], latestRun:null, policy:null, settings:null, send:null, supportCursor:null, historyCursor:null };
const text = (tag,value,cls) => {const el=document.createElement(tag);el.textContent=String(value??'');if(cls)el.className=cls;return el};
const pretty = value => JSON.stringify(value,null,2);
const time = value => value ? (Number.isNaN(new Date(value).getTime())?'日時を確認できません':new Date(value).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',hour12:false})+' JST') : '未記録';
function notice(message,error=false){$('notice').textContent=message;$('notice').className=error?'error':''}
async function api(path,options={}){
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);
  try{const response=await fetch(path,{...options,signal:options.signal||controller.signal,headers:{'Content-Type':'application/json','X-CSRF-Token':state.csrf,...options.headers}});const responseText=await response.text();let result;try{result=JSON.parse(responseText)}catch{const error=new Error(`管理API HTTP ${response.status}: JSON応答を取得できませんでした`);error.httpStatus=response.status;error.responseText=responseText;throw error}if(!response.ok){const error=new Error(result.error?.message||`管理API HTTP ${response.status}`);error.httpStatus=response.status;error.responseText=responseText;throw error}return result}catch(error){if(error.name==='AbortError')throw new Error('管理APIの応答を15秒以内に確認できませんでした。操作の実行成否は履歴で確認してください。');throw error}finally{clearTimeout(timer)}
}
function raw(target,value,open=true,label='原文・全フィールド'){const d=document.createElement('details');d.open=open;d.append(text('summary',label),text('pre',pretty(value)));target.append(d)}
function clear(id){$(id).replaceChildren();return $(id)}
function link(url,label){try{const u=new URL(url);if(!['https:','http:'].includes(u.protocol))return text('span',label);const el=text('a',label);el.href=u.href;el.target='_blank';el.rel='noopener noreferrer';return el}catch{return text('span',label)}}
function download(value,name){const b=new Blob([pretty(value)],{type:'application/json'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function show(view){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==view);document.querySelectorAll('nav button').forEach(el=>el.classList.toggle('active',el.dataset.view===view));location.hash=view;if(view==='history')history();if(view==='diagnostics')diagnostics();}
function table(target,rows,columns,onSelect){if(!rows.length){target.append(text('p','該当する記録はありません。計測開始以前や記録欠落の可能性は計測状態で確認してください。','muted'));return}const wrap=document.createElement('div');wrap.className='table-wrap';const t=document.createElement('table');const head=document.createElement('tr');for(const [label]of columns)head.append(text('th',label));t.append(head);for(const item of rows){const row=document.createElement('tr');for(const[,get]of columns){const td=document.createElement('td');const v=get(item);if(v instanceof Node)td.append(v);else td.textContent=String(v??'');row.append(td)}if(onSelect){const td=document.createElement('td');const b=text('button','詳細');b.addEventListener('click',guarded(()=>onSelect(item)));td.append(b);row.append(td)}t.append(row)}wrap.append(t);target.append(wrap)}
async function runAction(type,input,target){notice(`${type} を受け付けています`);const idem=crypto.randomUUID();let action;try{action=await api('v1/actions',{method:'POST',body:pretty({type,input,idempotencyKey:idem})})}catch(e){notice(`受付結果を確認できません。操作履歴を確認してください。再送用キー: ${idem} / ${e.message}`,true);throw e}if(target){clear(target);raw($(target),action)}notice(`操作ID ${action.id} — ${action.status}`);for(let n=0;n<180&&['queued','running'].includes(action.status);n++){await new Promise(r=>setTimeout(r,1000));try{action=await api(`v1/actions/${action.id}`)}catch(e){notice(`接続が切れました。操作 ${action.id} はデーモン側で継続します。履歴で確認してください。`,true);throw e}if(target){clear(target);renderAction($(target),action)}}notice(`${type}: ${action.status} / ${action.id}`,['failed','unknown'].includes(action.status));return action}
function renderAction(target,action){target.append(text('p',`${action.status} · ${action.id} · ${time(action.updatedAt)}`,action.status==='unknown'||action.status==='failed'?'error':''));if(action.error)raw(target,action.error,true,'エラー・成否不明の根拠');const data=action.result;if(data?.steps?.length&&action.type?.startsWith('url.'))preview(target,data.steps);raw(target,data??action,true,'結果の全フィールド');}
function preview(target,steps){for(const[at,step]of(steps||[]).entries()){const payload=step.payload||step.options||step.data||step;const box=document.createElement('div');box.className='message';box.append(text('small',`出力 ${at+1}`,'muted'));if(payload.content)box.append(text('div',payload.content));for(const embed of payload.embeds||[]){const e=embed.data||embed;const card=document.createElement('div');card.className='embed';if(e.author?.name)card.append(text('small',e.author.name));if(e.title)card.append(e.url?link(e.url,e.title):text('strong',e.title));if(e.description)card.append(text('p',e.description));for(const field of e.fields||[])card.append(text('strong',field.name),text('p',field.value));for(const img of[e.image?.url,e.thumbnail?.url].filter(Boolean)){if(String(img).startsWith('https://')){const image=document.createElement('img');image.src=img;image.loading='lazy';image.referrerPolicy='no-referrer';image.className='preview-image';card.append(image)}}box.append(card)}for(const file of payload.files||[]){const url=typeof file==='string'?file:file.attachment||file.url;box.append(typeof url==='string'?link(url,`添付: ${file.name||url}`):text('p',`添付: ${pretty(file)}`))}for(const row of payload.components||[]){const group=document.createElement('div');group.className='preview-actions';for(const cmp of(row.components||row.data?.components||[])){const c=cmp.data||cmp;group.append(c.url?link(c.url,c.label||'リンク'):text('span',c.label||c.custom_id||'操作ボタン','badge'))}box.append(group)}raw(box,payload,false,'送信payload');target.append(box)}}
function durationLabel(value){if(value==null)return '未計測';return value>=1000?`${(value/1000).toFixed(2)} 秒`:`${Number(value).toFixed(0)} ms`}
function probeLabel(probe){if(!probe?.configured)return '未設定';if(probe.ok===true)return `正常${probe.status?' (HTTP '+probe.status+')':''}`;if(probe.ok===false)return `応答失敗${probe.status?' (HTTP '+probe.status+')':''}`;return '未観測'}
function sectionFailure(id,title,error){const target=clear(id);target.append(text('p',title,'error'),text('p',error.message||String(error),'error'));if(error.responseText)raw(target,{httpStatus:error.httpStatus,response:error.responseText},false,'管理APIの失敗応答')}
async function overview(){
  const values=await Promise.allSettled([api('v1/health'),api('v1/metrics'),api('v1/incidents?status=active')]);
  const health=values[0].status==='fulfilled'?values[0].value:null;
  const metrics=values[1].status==='fulfilled'?values[1].value:null;
  $('connection').textContent=health?`管理API応答あり · ${time(health.time)}${values.some(v=>v.status==='rejected')?' · 一部情報の取得失敗':''}`:'管理APIの接続・取得に失敗';
  if(metrics){try{renderOverviewMetrics(metrics)}catch(error){sectionFailure('metric-cards','統計の表示に失敗しました',error);clear('metric-detail')}}else{sectionFailure('metric-cards','統計を取得できません。0件とは扱いません。',values[1].reason);clear('metric-detail')}
  if(health){try{renderOverviewHealth(health,metrics)}catch(error){sectionFailure('health','稼働状態の表示に失敗しました',error)}}else sectionFailure('health','現在の稼働状態を確認できません。',values[0].reason);
  if(values[2].status==='fulfilled'){try{renderOverviewIncidents(values[2].value)}catch(error){sectionFailure('incidents','障害一覧の表示に失敗しました',error)}}else sectionFailure('incidents','障害一覧を取得できません。障害なしとは判断しません。',values[2].reason);
}
function renderOverviewMetrics(metrics){
    const measurement=globalThis.CBTEView.measurement(metrics);const cards=clear('metric-cards');const pct=metrics.fullSuccess.ratio==null?'対象なし':`${(metrics.fullSuccess.ratio*100).toFixed(2)}%`;
    const definitions=[
      ['展開要求数',metrics.requestCount,'対象URLごとの根要求。取得の再試行や送信回数は加算しません。',''],
      ['完全成功を確認できた割合',pct,`完全成功 ${metrics.fullSuccess.numerator} 件 / 評価対象 ${metrics.fullSuccess.denominator} 件`,'F'],
      ['問題のある要求',metrics.problemRequestCount,'代替成功・部分成功・処理失敗・対象制約・結果不明の合計。','D,P,E,U,X'],
      ['設定による見送り',metrics.skippedRequestCount,'設定判定によって処理しなかった要求。根拠は要求詳細で確認できます。','S'],
      ['影響サーバー数',metrics.affectedGuildCount,`問題のある要求が発生したサーバー。サーバー不明の要求: ${metrics.affectedUnknownGuildRequests} 件`,'D,P,E,U,X'],
      ['実行中 / 結果不明',`${metrics.outcomes.I} / ${metrics.outcomes.X}`,'完了していない要求と、確認できなかった結果を分けて表示します。','I,X']
    ];
    for(const[label,value,detail,outcome]of definitions){const card=document.createElement('div');card.className='card';card.append(text('small',label),text('strong',measurement.unavailable?'未計測':value),text('small',measurement.unavailable?'本番の計測記録を確認できません。':detail));const button=text('button','該当する要求を見る');button.disabled=measurement.unavailable;button.addEventListener('click',()=>{state.supportWindow={from:metrics.from,to:metrics.to};$('support-guild').value='';$('support-from').value=localDate(metrics.from);$('support-to').value=localDate(metrics.to);$('support-kind').value='runs';$('support-outcome').value=outcome;$('support-window-note').textContent=`概要と同じ期間: ${time(metrics.from)} ～ ${time(metrics.to)}`;show('support');search()});card.append(button);cards.append(card)}
    const detail=clear('metric-detail');detail.append(text('p',measurement.message,measurement.unavailable?'error':'muted'),text('p',measurement.collection,metrics.coverage?.collectionState==='recent_heartbeat'?'muted':'error'));detail.append(text('p',`対象期間: ${time(metrics.from)} ～ ${time(metrics.to)} / 集計時点: ${time(metrics.snapshotAt)}`));
    const outcomeRows=Object.entries(metrics.outcomes).map(([code,count])=>({code,label:metrics.outcomeLabels?.[code]||code,count}));
    table(detail,outcomeRows,[['要求の結果',row=>row.label],['要求数',row=>measurement.unavailable?'未計測':String(row.count)+' 件']]);
    detail.append(text('h3','完了までの処理時間'));
    detail.append(text('p','要求の受付から結果確定までを、結果ごとに分けて集計します。P50は中央付近、P95は95%の処理が収まる時間です。'));
    const latencies=Object.entries(metrics.latencyByOutcome||{}).map(([code,value])=>({...value,label:metrics.outcomeLabels?.[code]||code}));
    if(latencies.length)table(detail,latencies,[['要求の結果',row=>row.label],['計測できた要求',row=>`${row.sampleCount} 件`],['P50',row=>durationLabel(row.p50Ms)],['P95',row=>durationLabel(row.p95Ms)]]);else detail.append(text('p','処理時間を計測できた完了要求はまだありません。','muted'));
    detail.append(text('p','見送り・取消・実行中は完全成功割合の評価対象から外し、件数を別に表示します。結果不明は評価対象に含めます。閲覧やリンククリックを示す指標ではありません。'));
    raw(detail,{outcomes:metrics.outcomes,latencyByOutcome:metrics.latencyByOutcome,byProvider:metrics.byProvider,excluded:metrics.excluded,coverage:metrics.coverage},false,'指標の原データ・プロバイダー別内訳');
}
function renderOverviewHealth(health,metrics){
    const healthRoot=clear('health');const snapshot=health.snapshot||{};const unit=snapshot.unit||{};const unitLabels={active:'稼働中',inactive:'停止',failed:'失敗',activating:'起動中',deactivating:'停止中'};
    table(healthRoot,[['管理API','応答あり'],['監視記録の保存',({progressing:'更新を確認',stalled:'更新停止',not_observed:'未観測'}[health.monitor?.state]||'未確認')],['監視記録の最終保存',time(health.monitor?.lastPersistedAt)],['Botプロセス',unitLabels[unit.ActiveState]||'未観測'],['Bot進捗の最終記録',snapshot.heartbeatAgeSeconds==null?'未観測':`${Math.round(snapshot.heartbeatAgeSeconds)} 秒前`],['通常ダッシュボード（ローカル）',probeLabel(snapshot.localHTTP)],['通常ダッシュボード（公開経路）',probeLabel(snapshot.publicHTTP)],['待機・実行中の管理操作',`${health.pendingActions} 件`],['成否不明の管理操作',`${health.unknownActions} 件`],['最初の要求記録',time(metrics?.coverage?.firstRecordedRequestAt)],['最新の要求記録',time(metrics?.coverage?.latestRecordedRequestAt)]],[['確認項目',row=>row[0]],['確認できた状態',row=>row[1]]]);
    healthRoot.append(text('p','件数は保存できた要求に基づきます。未記録の期間を正常と判断しないでください。','muted'));raw(healthRoot,{...health,coverage:metrics?.coverage},false,'稼働・計測状態の全フィールド');
}
function renderOverviewIncidents(incidents){
    const root=clear('incidents');if(!incidents.items.length)root.append(text('p','進行中の障害は記録されていません。監視対象の正常動作を保証する表示ではありません。計測状態と個別要求も確認してください。','muted'));else table(root,incidents.items,[['障害',v=>v.title],['状態',v=>({Confirmed:'発生を確認',Investigating:'調査中',Verifying:'復旧を確認中',Resolved:'復旧確認済み'}[v.status]||v.status)],['発生',v=>time(v.createdAt)]],v=>{raw(root,v,true);const b=text('button','確認済みにする');b.addEventListener('click',async()=>{await api(`v1/incidents/${v.id}/acknowledge`,{method:'POST',body:'{}'});overview()});root.append(b)});
}
async function history(cursor=null){try{const data=await api('v1/actions?limit=50'+(cursor?'&cursor='+encodeURIComponent(cursor):''));const target=cursor?$('history-list'):clear('history-list');table(target,data.items,[['受付',v=>time(v.createdAt)],['操作',v=>v.type],['状態',v=>v.status],['実行者',v=>`${v.actor} (${v.initiatedVia})`]],async item=>{const result=await api('v1/actions/'+item.id);renderAction(clear('history-detail'),result);if(result.type==='url.inspect'&&result.result){const b=text('button','検証画面に開く');b.addEventListener('click',()=>{renderInspection(result.result);show('inspect')});$('history-detail').prepend(b)}});state.historyCursor=data.nextCursor;$('history-more').hidden=!data.nextCursor}catch(e){notice(e.message,true)}}
function localDate(date){const d=new Date(date);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
async function search(cursor=null){try{const params=new URLSearchParams({guildId:$('support-guild').value,from:state.supportWindow?.from||new Date($('support-from').value).toISOString(),to:state.supportWindow?.to||new Date($('support-to').value).toISOString(),limit:'100'});if(cursor)params.set('cursor',cursor);const kind=$('support-kind').value;if(kind==='runs'&&$('support-outcome')?.value)params.set('outcome',$('support-outcome').value);const data=await api(`v1/${kind}?${params}`);const target=cursor?$('support-results'):clear('support-results');table(target,data.items,kind==='runs'?[['開始',v=>time(v.firstAt)],['処理ID',v=>v.id],['サーバー',v=>v.guildId],['結果',v=>globalThis.CBTEView.outcomes[v.outcome]||v.outcome||'詳細を参照'],['記録数',v=>v.eventCount]]:[['発生',v=>time(v.occurredAt)],['種類',v=>v.kind],['処理ID',v=>v.runId]],async v=>{const result=kind==='runs'?await api('v1/runs/'+v.id):v;const source=kind==='runs'?v:(v.payload||{});state.supportContext={guildId:source.guildId||source.guild_id||$('support-guild').value,channelId:source.channelId||source.channel_id||'',userId:source.userId||source.user_id||''};globalThis.CBTEEvidences.run(clear('run-detail'),result)});state.supportCursor=data.nextCursor;$('support-more').hidden=!data.nextCursor}catch(e){notice(e.message,true)}}
function inspectionInput(){
  const overrides=JSON.parse($('inspect-overrides')?.value||'{}');if(!overrides||typeof overrides!=='object'||Array.isArray(overrides))throw new Error('この実行用の設定はJSONオブジェクトで指定してください');
  if($('inspect-force-enable')?.checked)overrides.enabled=true;
  const input={url:$('inspect-url').value,guildId:$('inspect-guild').value||undefined,channelId:$('inspect-channel').value||undefined,userId:$('inspect-user').value||undefined,settingsOverrides:overrides};
  let hostname='';try{hostname=new URL(input.url).hostname.replace(/^www[.]/,'')}catch{}
  if(['x.com','twitter.com','fxtwitter.com','vxtwitter.com'].includes(hostname)){const source=$('inspect-source')?.value;const fallback=$('inspect-source-fallback')?.value;if(source)input.sourceId=source;if(fallback&&fallback!=='default')input.sourceFallback=fallback==='true'}
  return input;
}
function renderInspection(result){state.latestRun=result;const p=clear('preview');p.append(text('p',`${result.outcome||''} · ${result.providerId||''} · ${durationLabel(result.durationMs)}`));if(result.reason)p.append(text('p',result.reason));if(result.reason==='provider_disabled'){p.append(text('p','現在の設定ではプロバイダーが無効なため、取得前に見送られました。'));const retry=text('button','この実行だけ有効化して再検証');retry.addEventListener('click',guarded(async()=>{$('inspect-force-enable').checked=true;$('inspect-url').value=result.url;const ac=await runAction('url.inspect',inspectionInput(),'api-output');if(ac.result)renderInspection(ac.result)}));p.append(retry)}if(result.error)raw(p,result.error,true,'解析エラー');preview(p,result.steps||result.planned_outputs);if(!(result.steps||[]).length)p.append(text('p','送信出力は生成されていません。判定理由とAPI応答を確認してください。'));raw(p,{settings:result.settings,context:result.context,plannedEffects:result.plannedEffects},false,'設定・判定・予定していた後処理');const output=clear('api-output');for(const[at,attempt]of(result.httpAttempts||[]).entries())globalThis.CBTEEvidences.http(output,attempt,`HTTP試行 ${at+1}`);globalThis.CBTEEvidences.events(output,result.events||[],{label:'取得・解析・判定の経過'});$('compare-settings').value=pretty(result.settings||{});for(const id of['reparse','compare','use-output','export-run'])$(id).disabled=false;}
function operationFields(input){const root=clear('operation-fields');root.className='field-grid';for(const[key,value]of Object.entries(input)){const label=text('label',key);let el;if(value!==null&&typeof value==='object'){el=document.createElement('textarea');el.value=pretty(value);el.rows=4;el.dataset.type='json'}else if(typeof value==='boolean'){el=document.createElement('input');el.type='checkbox';el.checked=value;el.dataset.type='boolean'}else{el=document.createElement('input');el.value=value??'';el.type=typeof value==='number'?'number':'text';el.dataset.type=typeof value==='number'?'number':'string'}el.dataset.key=key;label.append(el);root.append(label)}$('operation-json').value=pretty(input)}
function readFields(root){const out={};for(const el of root.querySelectorAll('[data-key]')){out[el.dataset.key]=el.dataset.type==='json'?JSON.parse(el.value):el.dataset.type==='boolean'?el.checked:el.dataset.type==='number'?Number(el.value):el.value}return out}
function selectOperation(){const item=state.catalog.find(v=>v.type===$('operation-type').value);if(!item)return;$('operation-description').textContent=item.available===false?item.unavailableReason:item.description;operationFields(item.inputExample);$('operation-execute').disabled=item.available===false;$('operation-execute').textContent=item.available===false?'この稼働環境では未対応':item.mutating?'対象と入力を確認して実行':'実行'}
function renderServiceControls(value){if(!value)return;let panel=$('service-controls');if(!panel){panel=document.createElement('article');panel.id='service-controls';panel.className='panel';$('operation-form').before(panel)}panel.replaceChildren(text('h2','この稼働環境で使えるサービス操作'),text('p',value.description||''));if(value.limitations?.length){const list=document.createElement('ul');for(const limitation of value.limitations)list.append(text('li',limitation));panel.append(list)}}
async function diagnostics(){try{const[p,n]=await Promise.all([api('v1/policies'),api('v1/notifications')]);state.policy=p;if($('policy-json'))$('policy-json').value=pretty(p);$('auto-investigate').checked=p.autoInvestigate;$('auto-restart').checked=p.autoRestartHungBot;if($('auto-pause-reports'))$('auto-pause-reports').checked=p.autoPauseReports;$('desired-state').value=p.desiredState;$('maintenance-until').value=p.maintenanceUntil?localDate(p.maintenanceUntil):'';raw(clear('notifications'),n,true)}catch(e){notice(e.message,true)}}
function renderSettings(data){state.settings=data;const meta=clear('settings-meta');meta.append(text('p',`${data.guildId} / ${data.providerId} · hash ${data.hash}`));const root=clear('settings-editor');root.className='field-grid';for(const[key,value]of Object.entries(data.settings||{})){const spec=(data.specs||[]).find(s=>(s.settingKey||s.key)===key);const label=text('label',`${key}${spec?.label?' · '+spec.label:''}`);let el;if(value!==null&&typeof value==='object'){el=document.createElement('textarea');el.value=pretty(value);el.rows=4;el.dataset.type='json'}else if(typeof value==='boolean'){el=document.createElement('input');el.type='checkbox';el.checked=value;el.dataset.type='boolean'}else{el=document.createElement('input');el.value=value??'';el.type=typeof value==='number'?'number':'text';el.dataset.type=typeof value==='number'?'number':'string'}el.dataset.key=key;label.append(el,text('small','既定値: '+pretty(data.defaults?.[key])));root.append(label)}const save=text('button','変更内容を保存');root.append(save);}
function preparedSend(){const mode=$('send-mode').value;const input={guildId:$('send-guild').value,channelId:$('send-channel').value,mode,purpose:$('send-purpose').value,replyTo:$('send-reply').value||undefined};if(mode==='manual')input.payload={...JSON.parse($('send-payload').value),content:$('send-content').value};if(mode==='url')input.url=$('send-url').value;if(mode==='captured'){if(!state.latestRun?.steps?.length)throw new Error('先にURL検証で出力を生成してください');input.steps=state.latestRun.steps;input.sourceRunId=state.latestRun.runId}return input}
async function boot(){
  let session;try{session=await api('auth/session')}catch(error){$('login').hidden=false;$('app').hidden=true;$('connection').textContent=error.httpStatus===401?'ログインしてください':'管理APIへの接続を確認できません';if(error.httpStatus!==401)$('login-error').textContent=error.message;return}
  state.csrf=session.csrf;$('login').hidden=true;$('app').hidden=false;$('logout').hidden=false;overview();show(location.hash.slice(1)||'overview');
  try{const c=await api('v1/catalog');state.catalog=c.actions;renderServiceControls(c.serviceControls);const select=$('operation-type');select.replaceChildren();for(const item of c.actions){const option=text('option',`${item.label} (${item.type})${item.available===false?' · この環境では未対応':''}`);option.value=item.type;select.append(option)}selectOperation()}catch(error){notice('操作カタログを取得できません。'+error.message,true)}
}
function guarded(fn){return async event=>{event?.preventDefault();try{await fn(event)}catch(e){notice(e.message,true)}}}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();try{const s=await api('auth/login',{method:'POST',body:pretty({password:$('password').value})});state.csrf=s.csrf;$('password').value='';$('login-error').textContent='';await boot()}catch(e){$('login-error').textContent=e.message}});
$('logout').addEventListener('click',guarded(async()=>{await api('auth/logout',{method:'POST',body:'{}'});location.reload()}));document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
$('refresh-overview').addEventListener('click',overview);$('refresh-history').addEventListener('click',()=>history());$('history-more').addEventListener('click',()=>history(state.historyCursor));$('support-form').addEventListener('submit',guarded(()=>search()));$('support-more').addEventListener('click',()=>search(state.supportCursor));
$('inspect-form').addEventListener('submit',guarded(async()=>{const ac=await runAction('url.inspect',inspectionInput(),'api-output');if(ac.result)renderInspection(ac.result)}));
$('reparse').addEventListener('click',guarded(async()=>{const r=state.latestRun;const ac=await runAction('url.reparse',{...inspectionInput(),url:r.url,settings:r.settings,httpAttempts:r.httpAttempts,context:r.context},'api-output');if(ac.result)renderInspection(ac.result)}));
$('compare').addEventListener('click',guarded(async()=>{const r=state.latestRun;const ac=await runAction('url.compare',{...inspectionInput(),url:r.url,httpAttempts:r.httpAttempts,context:r.context,baselineSettings:r.settings,candidateSettings:JSON.parse($('compare-settings').value)},'comparison');if(ac.result?.candidate){const target=clear('comparison');target.append(text('p',ac.result.changed?'出力に差があります':'出力に差はありません'));preview(target,ac.result.candidate.steps);raw(target,ac.result,false)}}));
$('use-output').addEventListener('click',()=>{$('send-guild').value=$('inspect-guild').value;$('send-channel').value=$('inspect-channel').value;$('send-mode').value='captured';state.send=null;show('send')});$('export-run').addEventListener('click',()=>download(state.latestRun,`cbte-run-${state.latestRun.runId}.json`));
$('resolve').addEventListener('click',guarded(async()=>{await runAction('message.resolve',{guildId:$('send-guild').value,channelId:$('send-channel').value},'destination')}));
$('prepare-send').addEventListener('click',guarded(async()=>{state.send=preparedSend();raw(clear('send-review'),state.send,true,'この内容を送信します');$('send-confirm').hidden=false}));
$('send-form').addEventListener('input',()=>{state.send=null;$('send-confirm').hidden=true});$('send-form').addEventListener('submit',guarded(async()=>{if(!state.send)throw new Error('送信内容を確認してください');$('send-confirm').disabled=true;try{await runAction('message.send',state.send,'send-result')}finally{state.send=null;$('send-confirm').hidden=true;$('send-confirm').disabled=false}}));
$('settings-form').addEventListener('submit',guarded(async()=>{const ac=await runAction('settings.get',{guildId:$('settings-guild').value,providerId:$('settings-provider').value},'settings-result');if(ac.status==='succeeded')renderSettings(ac.result)}));
$('settings-editor').addEventListener('submit',guarded(async()=>{if(!state.settings)return;const values=readFields($('settings-editor'));const changes={};for(const[k,v]of Object.entries(values))if(pretty(v)!==pretty(state.settings.settings[k]))changes[k]=v;if(!Object.keys(changes).length){notice('変更はありません');return}const ac=await runAction('settings.change',{guildId:state.settings.guildId,providerId:state.settings.providerId,expectedHash:state.settings.hash,changes},'settings-result');if(ac.status==='succeeded'){const reload=await runAction('settings.get',{guildId:state.settings.guildId,providerId:state.settings.providerId},'settings-result');if(reload.result)renderSettings(reload.result)}}));
$('operation-type').addEventListener('change',selectOperation);$('operation-apply-json').addEventListener('click',guarded(()=>operationFields(JSON.parse($('operation-json').value))));$('operation-form').addEventListener('submit',guarded(async()=>{const input=readFields($('operation-fields'));$('operation-json').value=pretty(input);await runAction($('operation-type').value,input,'operation-result')}));
$('collect').addEventListener('click',guarded(()=>runAction('diagnostics.collect',{},'diagnostic-result')));$('db-diagnose').addEventListener('click',guarded(()=>runAction('diagnostics.db',{},'diagnostic-result')));$('refresh-diagnostics').addEventListener('click',diagnostics);
$('policy-form').addEventListener('submit',guarded(async()=>{const p=state.policy;if(!p)throw new Error('ポリシーを取得してください');state.policy=await api('v1/policies',{method:'PUT',body:pretty({...p,expectedRevision:p.revision,autoInvestigate:$('auto-investigate').checked,autoRestartHungBot:$('auto-restart').checked,autoPauseReports:$('auto-pause-reports')?.checked??p.autoPauseReports,desiredState:$('desired-state').value,maintenanceUntil:$('maintenance-until').value?new Date($('maintenance-until').value).toISOString():''})});notice('ポリシーを保存しました')}));
$('password-form').addEventListener('submit',guarded(async()=>{await api('v1/account/password',{method:'POST',body:pretty({password:$('new-password').value})});location.reload()}));
$('support-from').value=localDate(Date.now()-3600000);$('support-to').value=localDate(Date.now());const params=new URLSearchParams(location.search);for(const[field,param]of[['support-guild','guildId'],['inspect-guild','guildId'],['inspect-channel','channelId']])if(params.has(param))$(field).value=params.get(param);boot();

// Completed reports use an independent worker queue and survive Bot/DB outages.
const reportsButton=text('button','詳細レポート');reportsButton.dataset.view='reports';reportsButton.addEventListener('click',()=>show('reports'));$('nav').append(reportsButton);
const outcomeFilterLabel=text('label','要求の結果');const outcomeFilter=document.createElement('select');outcomeFilter.id='support-outcome';for(const[value,label]of[['','すべて'],['F','完全成功'],['D,P,E,U,X','問題のある要求'],['D','代替成功'],['P','部分成功'],['E','処理失敗'],['U','取得対象の制約'],['S','設定による見送り'],['C','明示的取消'],['I,X','実行中・結果不明'],['I','実行中'],['X','結果不明']]){const option=text('option',label);option.value=value;outcomeFilter.append(option)}outcomeFilterLabel.append(outcomeFilter);$('support-form').insertBefore(outcomeFilterLabel,$('support-form').querySelector('button'));const supportWindowNote=text('p','','muted');supportWindowNote.id='support-window-note';$('support-form').after(supportWindowNote);for(const id of ['support-from','support-to'])$(id).addEventListener('input',()=>{state.supportWindow=null;supportWindowNote.textContent=''});
const pauseLabel=text('label','I/O資源圧迫が続く場合、新しい重いレポートを5分間自動保留');const pauseInput=document.createElement('input');pauseInput.type='checkbox';pauseInput.id='auto-pause-reports';pauseLabel.prepend(pauseInput);$('policy-form').prepend(pauseLabel);
const sourceLabel=text('label','取得元を指定 (X)');const sourceSelect=document.createElement('select');sourceSelect.id='inspect-source';for(const[id,label]of[['','稼働中の取得元設定を使用'],['vxtwitter','vxtwitter'],['fxtwitter','fxtwitter']]){const option=text('option',label);option.value=id;sourceSelect.append(option)}sourceLabel.append(sourceSelect);$('inspect-form').insertBefore(sourceLabel,$('inspect-form').querySelector('button'));
const inspectorExtras=document.createElement('div');inspectorExtras.className='panel';
inspectorExtras.innerHTML='<label>検証の対象<select id="inspect-context-preset"><option value="entered">入力したサーバー・チャンネルを使用</option><option value="url-only">URLの取得・解析だけを検証</option><option value="support">サーバー調査で選んだ対象IDを使用</option><option value="settings">設定画面のサーバーIDを使用</option><option value="last-run">直前の検証と同じ対象IDを使用</option></select></label><p id="inspect-context-note" class="muted"></p><label><input id="inspect-force-enable" type="checkbox" checked> この実行だけプロバイダーを有効化する</label><p class="muted">無効なプロバイダーも取得・解析を検証できます。サーバーの保存済み設定は変更しません。設定による見送りも再現する場合はチェックを外してください。</p><label>この実行用の設定上書き (JSON)<textarea id="inspect-overrides" rows="5">{}</textarea></label><p class="muted">指定した項目だけを現在のサーバー設定へ重ねます。サーバーIDがなければプロバイダーの既定値を使います。有効化チェック中は enabled を true にします。</p><label>Xの別取得元への切り替え<select id="inspect-source-fallback"><option value="default">現在の取得元設定に従う</option><option value="true">許可する</option><option value="false">許可しない</option></select></label>';
$('inspect-form').insertBefore(inspectorExtras,sourceLabel);
function inspectionContextNote(){const guild=$('inspect-guild').value;const channel=$('inspect-channel').value;const user=$('inspect-user').value;let message= guild?`サーバー ${guild} の現在の設定を読み取ります。`:'サーバー未指定: プロバイダー既定値を使用します。';message+=guild&&channel?' チャンネル・権限・NSFW状態は実行時にDiscordから確認します。':' チャンネル・権限・NSFW状態は未確認として表示します。';message+=user&&guild&&channel?' 指定ユーザーの現在のロールも取得します。':' 対象ユーザーのロールは未確認です。';$('inspect-context-note').textContent=message}
for(const id of ['inspect-guild','inspect-channel','inspect-user'])$(id).addEventListener('input',inspectionContextNote);
$('inspect-context-preset').addEventListener('change',guarded(()=>{const preset=$('inspect-context-preset').value;let context;if(preset==='url-only'){context={};$('inspect-force-enable').checked=true}else if(preset==='support'){context=state.supportContext||{guildId:$('support-guild').value};if(!context.guildId)throw new Error('先にサーバー調査で対象を指定してください');$('inspect-force-enable').checked=false}else if(preset==='settings'){context={guildId:$('settings-guild').value};if(!context.guildId)throw new Error('設定画面にサーバーIDを指定してください');$('inspect-force-enable').checked=false}else if(preset==='last-run'){if(!state.latestRun?.context)throw new Error('先に検証を実行してください');context=state.latestRun.context;$('inspect-force-enable').checked=false}if(context){$('inspect-guild').value=context.guildId||'';$('inspect-channel').value=context.channelId||'';$('inspect-user').value=context.userId||''}inspectionContextNote()}));inspectionContextNote();
const policyDetails=document.createElement('details');policyDetails.append(text('summary','全自動処理ポリシーを確認・編集'));const policyJSON=document.createElement('textarea');policyJSON.id='policy-json';policyJSON.rows=14;const policySave=text('button','JSONの全ポリシーを保存');policySave.type='button';policySave.addEventListener('click',guarded(async()=>{if(!state.policy)throw new Error('現在のポリシーを取得してください');const input=JSON.parse(policyJSON.value);state.policy=await api('v1/policies',{method:'PUT',body:pretty({...input,expectedRevision:state.policy.revision})});await diagnostics();notice('全ポリシーを保存しました')}));policyDetails.append(policyJSON,policySave);$('policy-form').append(policyDetails);
const reportsView=document.createElement('section');reportsView.id='reports';reportsView.className='view';reportsView.hidden=true;
reportsView.innerHTML='<h1>詳細レポート</h1><p>完成したレポートと生成状態を表示します。更新失敗時も直前の完成版を残します。</p><form id="reports-form" class="panel"><label>種類<select id="reports-kind"><option value="overview">管理概要</option><option value="analytics">詳細統計</option><option value="guild-preview">サーバー分析</option><option value="provider-preview">プロバイダー分析</option></select></label><label>集計条件 (JSON)<textarea id="reports-filters" rows="6">{}</textarea></label><div class="toolbar"><button type="button" id="reports-load">完成版・状態を取得</button><button>更新を要求</button><button type="button" id="reports-export">完成版を保存</button></div></form><article class="panel"><div id="reports-state"></div><div id="reports-output"></div></article>';
$('app').append(reportsView);let lastReport=null;
function renderReport(snapshot){lastReport=snapshot.report;raw(clear('reports-state'),{kind:snapshot.kind,key:snapshot.key,actionId:snapshot.actionId,status:snapshot.status,cache:snapshot.cache,metadata:snapshot.metadata},true,'完成版と生成状態');const target=clear('reports-output');if(!snapshot.report){target.append(text('p','完成版はまだありません。生成状態を更新してください。'));return}for(const[key,value]of Object.entries(snapshot.report)){const section=document.createElement('details');section.open=false;section.append(text('summary',key));if(Array.isArray(value)&&value.length&&typeof value[0]==='object'){const keys=[...new Set(value.flatMap(v=>Object.keys(v||{})))];table(section,value,keys.map(k=>[k,v=>typeof v[k]==='object'?pretty(v[k]):v[k]]))}else raw(section,value,true,'データ');target.append(section)}}
async function reportRequest(force){const kind=$('reports-kind').value;const filters=JSON.parse($('reports-filters').value);const snapshot=force?await api(`v1/reports/${kind}`,{method:'POST',body:pretty({filters,force:true})}):await api(`v1/reports/${kind}?filters=${encodeURIComponent(pretty(filters))}`);renderReport(snapshot);if(force)notice(`レポート生成: ${snapshot.status} / ${snapshot.actionId||''}`)}
$('reports-load').addEventListener('click',guarded(()=>reportRequest(false)));$('reports-form').addEventListener('submit',guarded(()=>reportRequest(true)));$('reports-export').addEventListener('click',()=>{if(lastReport)download(lastReport,'cbte-report.json')});
