CREATE TABLE IF NOT EXISTS bot_provider_hourly_aggregates (
    bucket_start_ms BIGINT NOT NULL,
    bucket_size_seconds INT NOT NULL DEFAULT 3600,
    provider_id VARCHAR(64) NOT NULL DEFAULT '',
    account_key VARCHAR(191) NOT NULL DEFAULT '',
    guild_id VARCHAR(32) NOT NULL DEFAULT '',
    content_type VARCHAR(64) NOT NULL DEFAULT '',
    event_type VARCHAR(64) NOT NULL DEFAULT '',
    schema_version VARCHAR(64) NOT NULL DEFAULT '',
    content_events BIGINT UNSIGNED NOT NULL DEFAULT 0,
    analytics_events BIGINT UNSIGNED NOT NULL DEFAULT 0,
    extract_events BIGINT UNSIGNED NOT NULL DEFAULT 0,
    extract_successes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    extract_failures BIGINT UNSIGNED NOT NULL DEFAULT 0,
    send_events BIGINT UNSIGNED NOT NULL DEFAULT 0,
    send_successes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    send_failures BIGINT UNSIGNED NOT NULL DEFAULT 0,
    enrichment_jobs BIGINT UNSIGNED NOT NULL DEFAULT 0,
    enrichment_successes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    enrichment_failures BIGINT UNSIGNED NOT NULL DEFAULT 0,
    analytics_duration_sum_ms BIGINT UNSIGNED NOT NULL DEFAULT 0,
    analytics_duration_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    analytics_duration_max_ms INT UNSIGNED NOT NULL DEFAULT 0,
    enrichment_duration_sum_ms BIGINT UNSIGNED NOT NULL DEFAULT 0,
    enrichment_duration_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    enrichment_duration_max_ms INT UNSIGNED NOT NULL DEFAULT 0,
    media_count_sum BIGINT UNSIGNED NOT NULL DEFAULT 0,
    duration_seconds_sum BIGINT UNSIGNED NOT NULL DEFAULT 0,
    duration_seconds_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    sensitive_events BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (bucket_start_ms, provider_id, account_key, guild_id, content_type, event_type, schema_version),
    INDEX idx_provider_hourly_provider_time (provider_id, bucket_start_ms),
    INDEX idx_provider_hourly_account_time (provider_id, account_key, bucket_start_ms),
    INDEX idx_provider_hourly_guild_time (guild_id, bucket_start_ms),
    INDEX idx_provider_hourly_event_time (event_type, bucket_start_ms),
    INDEX idx_provider_hourly_schema_time (schema_version, bucket_start_ms)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bot_provider_hourly_unique_keys (
    bucket_start_ms BIGINT NOT NULL,
    provider_id VARCHAR(64) NOT NULL DEFAULT '',
    account_key VARCHAR(191) NOT NULL DEFAULT '',
    guild_id VARCHAR(32) NOT NULL DEFAULT '',
    content_type VARCHAR(64) NOT NULL DEFAULT '',
    event_type VARCHAR(64) NOT NULL DEFAULT '',
    key_type ENUM('author_user', 'guild', 'url') NOT NULL,
    key_hash CHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (bucket_start_ms, provider_id, account_key, guild_id, content_type, event_type, key_type, key_hash),
    INDEX idx_provider_hourly_unique_lookup (provider_id, account_key, bucket_start_ms, key_type),
    INDEX idx_provider_hourly_unique_guild (guild_id, bucket_start_ms, key_type)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
