CREATE TABLE IF NOT EXISTS bot_analytics_events (
    analytics_event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    occurred_at_ms BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    source VARCHAR(96) NULL,
    provider_id VARCHAR(64) NULL,
    account_key VARCHAR(191) NULL,
    endpoint_key VARCHAR(191) NULL,
    raw_url TEXT NULL,
    normalized_url TEXT NULL,
    url_hash CHAR(64) NULL,
    guild_id VARCHAR(32) NULL,
    guild_name_snapshot VARCHAR(255) NULL,
    channel_id VARCHAR(32) NULL,
    channel_name_snapshot VARCHAR(255) NULL,
    author_user_id VARCHAR(32) NULL,
    message_id VARCHAR(32) NULL,
    command_name VARCHAR(64) NULL,
    component_id VARCHAR(191) NULL,
    success TINYINT(1) NULL,
    duration_ms INT UNSIGNED NULL,
    count BIGINT UNSIGNED NOT NULL DEFAULT 1,
    details_json LONGTEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_analytics_time (occurred_at_ms),
    INDEX idx_analytics_event_time (event_type, occurred_at_ms),
    INDEX idx_analytics_provider_account_time (provider_id, account_key, occurred_at_ms),
    INDEX idx_analytics_url_hash (url_hash),
    INDEX idx_analytics_guild_time (guild_id, occurred_at_ms),
    INDEX idx_analytics_user_time (author_user_id, occurred_at_ms),
    INDEX idx_analytics_command_time (command_name, occurred_at_ms),
    INDEX idx_analytics_component_time (component_id, occurred_at_ms)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bot_provider_content_events (
    content_event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    occurred_at_ms BIGINT NOT NULL,
    provider_id VARCHAR(64) NOT NULL,
    account_key VARCHAR(191) NULL,
    content_id VARCHAR(191) NULL,
    content_type VARCHAR(64) NULL,
    content_url TEXT NULL,
    normalized_url TEXT NULL,
    url_hash CHAR(64) NULL,
    title TEXT NULL,
    description_preview TEXT NULL,
    author_name VARCHAR(255) NULL,
    language VARCHAR(32) NULL,
    published_at_ms BIGINT NULL,
    `sensitive` TINYINT(1) NULL,
    media_count INT UNSIGNED NULL,
    duration_seconds INT UNSIGNED NULL,
    guild_id VARCHAR(32) NULL,
    channel_id VARCHAR(32) NULL,
    author_user_id VARCHAR(32) NULL,
    source VARCHAR(96) NULL,
    raw_metrics_json LONGTEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_content_provider_account_time (provider_id, account_key, occurred_at_ms),
    INDEX idx_content_provider_type_time (provider_id, content_type, occurred_at_ms),
    INDEX idx_content_guild_time (guild_id, occurred_at_ms),
    INDEX idx_content_user_time (author_user_id, occurred_at_ms),
    INDEX idx_content_url_hash (url_hash)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bot_provider_content_facets (
    facet_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    content_event_id BIGINT UNSIGNED NOT NULL,
    provider_id VARCHAR(64) NOT NULL,
    account_key VARCHAR(191) NULL,
    facet_key VARCHAR(191) NOT NULL,
    facet_value VARCHAR(512) NULL,
    numeric_value DOUBLE NULL,
    json_value LONGTEXT NULL,
    occurred_at_ms BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_content_facets_key_value_time (facet_key, facet_value, occurred_at_ms),
    INDEX idx_content_facets_provider_key_time (provider_id, facet_key, occurred_at_ms),
    INDEX idx_content_facets_account_key_time (provider_id, account_key, facet_key, occurred_at_ms),
    CONSTRAINT fk_content_facets_event
        FOREIGN KEY (content_event_id) REFERENCES bot_provider_content_events(content_event_id)
        ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
