"use client";

import { useEffect, useState } from "react";
import type { AutomationApi } from "./rule-editor";
const field = "w-full rounded border bg-background px-3 py-2 text-sm";
const button = "rounded border bg-background px-3 py-2 text-sm hover:bg-muted disabled:opacity-40";
const modes: Record<string, string> = { contains: "部分一致", word: "単語単位", exact: "完全一致", prefix: "先頭一致", suffix: "末尾一致" };
const entryObject = (entry: any, mode: string) => ({ term: typeof entry === "string" ? entry : entry.term, kind: entry.kind || "deny", mode: entry.mode || mode || "contains", category: entry.category || "", severity: entry.severity ?? 0, replacement: entry.replacement || "" });
const dictionaryMetadata = (data: any) => ({ name: data.name, mode: data.mode || "contains", normalization: data.normalization || { form: "NFKC", caseFold: true, spaces: "preserve" }, source: data.source || "", license: data.license || "" });
function download(text: string, name: string) { const url = URL.createObjectURL(new Blob([text], { type: "text/plain;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }

export function DictionaryManager({ api, dictionaries, scope, canEdit, refresh }: { api: AutomationApi; dictionaries: any[]; scope: string; canEdit: boolean; refresh: () => Promise<void> }) {
  const [selected, setSelected] = useState<any>(null), [page, setPage] = useState<any>(null), [search, setSearch] = useState(""), [versions, setVersions] = useState<any[]>([]), [versionCursor, setVersionCursor] = useState<number | null>(null), [diff, setDiff] = useState<any>(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [text, setText] = useState(""), [fileName, setFileName] = useState(""), [format, setFormat] = useState("txt"), [name, setName] = useState("禁止語辞書"), [mode, setMode] = useState("contains"), [source, setSource] = useState(""), [license, setLicense] = useState("");
  const [preview, setPreview] = useState<any>(null), [deduplicate, setDeduplicate] = useState(true), [operations, setOperations] = useState<any[]>([]), [edit, setEdit] = useState<any>(null), [patchPreview, setPatchPreview] = useState<any>(null), [testText, setTestText] = useState(""), [matches, setMatches] = useState<any[] | null>(null);
  const [metadata, setMetadata] = useState<any>(null), [moreDictionaries, setMoreDictionaries] = useState<any[]>([]), [listCursor, setListCursor] = useState<string | null>(null);
  const [rules, setRules] = useState<any[] | null>(null), [ruleCursor, setRuleCursor] = useState<string | null>(null), [ruleId, setRuleId] = useState(""), [alias, setAlias] = useState("words");
  const writable = selected?.scope !== "guild" || canEdit;
  const current = page && page.revision === page.currentRevision;
  const dirty = operations.length > 0 || !!edit || !!(metadata && page && JSON.stringify(metadata) !== JSON.stringify(dictionaryMetadata(page)));
  useEffect(() => {
    if (!dirty) return;
    const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ""; };
    window.addEventListener("beforeunload", warn);
    return () => window.removeEventListener("beforeunload", warn);
  }, [dirty]);
  const task = async (work: () => Promise<void>) => { setBusy(true); setError(""); setNotice(""); try { await work(); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const importBody = () => ({ text, format, metadata: { name, mode, source, license }, deduplicate, scope });
  const invalidateImport = () => setPreview(null);
  async function read(item: any, offset = 0, revision?: number) {
    const nextSearch = selected?.id === item.id ? search : "";
    const result = await api(`dictionaries/${item.id}?offset=${offset}&search=${encodeURIComponent(nextSearch)}${revision ? `&revision=${revision}` : ""}`);
    setSearch(nextSearch); setDiff(null);
    if (selected?.id !== item.id) { setVersions([]); setVersionCursor(null); }
    setSelected({ ...item, name: result.name, revision: result.currentRevision, scope: result.scope }); setPage(result); setOperations([]); setPatchPreview(null); setEdit(null); setMatches(null);
    setMetadata(dictionaryMetadata(result));
  }
  const guardUnsaved = () => !dirty || confirm("未保存の語・辞書設定の変更を破棄して移動しますか？");
  async function loadVersions(before?: number) { const result = await api(`dictionaries/${selected.id}/versions${before ? `?before=${before}` : ""}`); setVersions(old => before ? [...old, ...result.items] : result.items); setVersionCursor(result.nextRevision); }
  async function loadRules(after?: string) {
    const result = await api(`workflows${after ? `?afterId=${after}` : ""}`);
    setRules(old => after ? [...(old || []), ...result.items] : result.items); setRuleCursor(result.nextCursor);
  }
  async function pinVersion() {
    if (dirty) throw new Error("未保存の変更を保存するか取り消してから、保存済みの版を割り当ててください。");
    const target = await api(`workflows/${ruleId}`);
    if (target.scope === "guild" && (!canEdit || selected.scope !== "guild")) throw new Error("サーバー共有ルールには、編集権限とサーバー共有の辞書が必要です。");
    const prior = target.bindings.dictionaries[alias];
    if (prior && (prior.id !== selected.id || prior.revision !== page.revision) && !confirm(`「${target.name}」の「${alias}」を、この辞書の版 ${page.revision} に置き換えますか？実行中の版は変わりません。`)) return;
    await api(`workflows/${target.id}`, "PATCH", { expectedRevision: target.revision, definition: target.draft, bindings: { ...target.bindings, dictionaries: { ...target.bindings.dictionaries, [alias]: { id: selected.id, revision: page.revision } } } });
    await refresh(); setNotice(`「${target.name}」の下書きに版 ${page.revision} を固定しました。実行中の版は変わりません。スタジオで確認してから適用してください。`);
  }
  function stageEdit() {
    const entry = { term: edit.value.term, kind: edit.value.kind, mode: edit.value.mode, ...(edit.value.category ? { category: edit.value.category } : {}), severity: Number(edit.value.severity), ...(edit.value.replacement ? { replacement: edit.value.replacement } : {}) };
    const operation = edit.index == null ? { op: "add", entry } : { op: "replace", index: edit.index, expected: edit.expected, entry };
    setOperations(old => [...old.filter(o => edit.index == null || o.index !== edit.index), operation]); setEdit(null); setPatchPreview(null);
  }
  async function patch(save: boolean) {
    const result = await api(`dictionaries/${selected.id}/patch`, "POST", { expectedRevision: page.currentRevision, preview: !save, deduplicate, patch: { operations, metadata } });
    if (!save) { setPatchPreview(result); return; }
    await refresh(); await read({ ...selected, revision: result.revision }); if (versions.length) await loadVersions(); setDiff(null); setNotice(`版 ${result.revision} として保存しました。既存ルールが参照する版は変わりません。`);
  }
  return <fieldset disabled={busy} className="min-w-0 space-y-4">
    {error && <p role="alert" className="rounded border border-destructive p-3 text-sm text-destructive">{error}</p>}{notice && <p role="status" className="rounded border p-3 text-sm">{notice}</p>}
    <details className="space-y-3 rounded border bg-card p-4" open={!selected}><summary className="font-semibold">辞書の一括取り込み（JSON / CSV / 1行1語）</summary>
      <p className="text-sm text-muted-foreground">最大100万語・本文128MiB。禁止語と許可語、照合方法、分類を保存できます。TXTは語だけ、JSON/自動化辞書CSVは詳細設定と出典も保存します。</p>
      <div className="grid gap-3 md:grid-cols-2"><label className="text-sm">辞書名<input className={field} value={name} onChange={e => { setName(e.target.value); invalidateImport(); }} /></label><label className="text-sm">取り込み形式<select className={field} value={format} onChange={e => { setFormat(e.target.value); invalidateImport(); }}><option value="txt">1行1語</option><option value="csv">CSV</option><option value="json">JSON</option></select></label><label className="text-sm">基本の照合方法<select className={field} value={mode} onChange={e => { setMode(e.target.value); invalidateImport(); }}>{Object.entries(modes).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label className="text-sm">出典<input className={field} value={source} onChange={e => { setSource(e.target.value); invalidateImport(); }} /></label><label className="text-sm">利用条件・ライセンス<input className={field} value={license} onChange={e => { setLicense(e.target.value); invalidateImport(); }} /></label></div>
      <input type="file" aria-label="辞書ファイル" accept=".json,.csv,.txt" onChange={e => { const file = e.target.files?.[0]; if (file) void task(async () => { if (file.size > 128 * 1024 * 1024) throw new Error("辞書は128MiBまでです。"); setText(await file.text()); setFileName(file.name); setFormat(file.name.toLowerCase().endsWith(".json") ? "json" : file.name.toLowerCase().endsWith(".csv") ? "csv" : "txt"); invalidateImport(); }); }} />
      {text.length <= 100000 ? <textarea aria-label="取り込む語または辞書データ" className={`${field} h-36 font-mono`} value={text} onChange={e => { setText(e.target.value); setFileName(""); invalidateImport(); }} /> : <p className="rounded bg-muted p-3 text-sm">{fileName || "辞書データ"} / {text.length.toLocaleString()}文字。大量データの本文表示は省略しています。検索・部分編集は保存後に利用できます。</p>}
      <label className="block text-sm"><input type="checkbox" checked={deduplicate} onChange={e => { setDeduplicate(e.target.checked); invalidateImport(); setPatchPreview(null); }} />同じ指定の重複語をまとめる（異なる指定の競合は保存前に停止）</label>
      <div className="flex flex-wrap gap-2"><button className={button} disabled={busy || !text} onClick={() => void task(async () => setPreview(await api("dictionary-preview", "POST", importBody())))}>取り込み内容を確認</button><button className={button} disabled={busy || !preview || preview.conflictCount > 0 || scope === "guild" && !canEdit} onClick={() => void task(async () => { const result = await api("dictionaries", "POST", importBody()); await refresh(); await read({ id: result.id, scope, name: preview.metadata.name }); setNotice("新しい辞書として保存しました。"); })}>新しい辞書として保存</button>{selected && <button className={button} disabled={busy || !preview || preview.conflictCount > 0 || !writable} onClick={() => { if (confirm(`「${selected.name || page?.name}」の新しい版として置き換えますか？以前の版とルールの版固定は残ります。`)) void task(async () => { const result = await api(`dictionaries/${selected.id}`, "PATCH", { ...importBody(), expectedRevision: selected.revision }); await refresh(); await read({ ...selected, revision: result.revision }); setNotice("新しい版を保存しました。ルールの参照版は変わりません。"); }); }}>選択した辞書の新しい版にする</button>}</div>
      {preview && <div className="rounded bg-muted p-3 text-sm"><p>{preview.metadata.name} / {preview.entryCount.toLocaleString()}語 / 重複 {preview.duplicateCount} / 競合 {preview.conflictCount}</p><pre className="max-h-44 overflow-auto whitespace-pre-wrap text-xs">{preview.conflictCount ? JSON.stringify(preview.conflicts, null, 2) : preview.sample.map((e: any) => typeof e === "string" ? e : JSON.stringify(e)).join("\n")}</pre></div>}
    </details>
    <section className="space-y-3 rounded border bg-card p-4"><h2 className="font-semibold">辞書一覧</h2><div className="flex flex-wrap gap-2">{[...dictionaries, ...moreDictionaries].filter((d, i, all) => all.findIndex(x => x.id === d.id) === i).map(d => <button key={d.id} data-dictionary-id={d.id} title={`辞書ID: ${d.id}`} aria-pressed={selected?.id === d.id} className={button} onClick={() => { if (guardUnsaved()) void task(async () => { await read(d); setVersions([]); setDiff(null); }); }}>{d.name} / v{d.revision} / {d.entryCount?.toLocaleString()}語</button>)}</div><button className={button} disabled={busy || moreDictionaries.length > 0 && !listCursor} onClick={() => void task(async () => { const result = await api(`dictionaries${listCursor ? `?afterId=${listCursor}` : ""}`); setMoreDictionaries(old => [...old, ...result.items]); setListCursor(result.nextCursor); })}>辞書一覧の続きを取得</button>
      {selected && page && <div className="space-y-3 border-t pt-3"><div className="flex flex-wrap gap-2"><h3 className="mr-auto font-semibold">{page.name} / 表示版 {page.revision} / 最新 {page.currentRevision}</h3>{["json", "csv", "txt"].map(f => <button key={f} className={button} disabled={busy} onClick={() => void task(async () => { const data = await api(`dictionaries/${selected.id}/export?format=${f}&revision=${page.revision}`); download(data.text, `dictionary-v${page.revision}.${f}`); })}>{f.toUpperCase()}出力</button>)}<button className={button} onClick={() => void task(() => loadVersions())}>版の履歴</button></div>
        {!current && <p className="text-sm text-amber-600">過去の版を表示中です。編集するには最新版を開くか、この版を新しい版として復元してください。</p>}
        <div className="flex gap-2"><input aria-label="辞書の語を検索" className={field} value={search} onChange={e => setSearch(e.target.value)} /><button className={button} disabled={busy} onClick={() => { if (guardUnsaved()) void task(() => read(selected, 0, page.revision)); }}>検索</button></div>
        <div className="max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>語</th><th>処理</th><th>照合</th><th>分類</th><th>操作</th></tr></thead><tbody>{page.records.map((record: any) => { const entry = entryObject(record.entry, page.mode), pending = operations.find(o => o.index === record.index); return <tr key={record.index} className="border-t"><td className="max-w-64 break-all py-2">{entry.term}{pending && <span className="ml-1 text-xs text-amber-600">変更予定</span>}</td><td>{entry.kind === "allow" ? "許可" : "禁止"}</td><td>{modes[entry.mode]}</td><td>{entry.category || "—"}</td><td className="space-x-2 whitespace-nowrap"><button disabled={!writable || !current} onClick={() => setEdit({ index: record.index, expected: record.entry, value: pending?.op === "replace" ? entryObject(pending.entry, page.mode) : entry })}>編集</button><button disabled={!writable || !current} onClick={() => { setOperations(old => [...old.filter(o => o.index !== record.index), { op: "remove", index: record.index, expected: record.entry }]); setPatchPreview(null); }}>削除予約</button></td></tr>; })}</tbody></table></div>
        <div className="flex flex-wrap gap-2 text-sm"><span>{page.total ? page.offset + 1 : 0}〜{Math.min(page.total, page.offset + page.records.length)} / {page.total.toLocaleString()}語</span><button className={button} disabled={busy || page.offset === 0} onClick={() => { if (guardUnsaved()) void task(() => read(selected, Math.max(0, page.offset - 100), page.revision)); }}>前の100語</button><button className={button} disabled={busy || page.nextOffset == null} onClick={() => { if (guardUnsaved()) void task(() => read(selected, page.nextOffset, page.revision)); }}>次の100語</button><button className={button} disabled={!writable || !current} onClick={() => setEdit({ value: entryObject("", page.mode) })}>語を追加</button></div>
        {edit && <div className="grid gap-2 rounded border p-3 md:grid-cols-3"><label className="text-sm">語<input className={field} value={edit.value.term} onChange={e => setEdit({ ...edit, value: { ...edit.value, term: e.target.value } })} /></label><label className="text-sm">処理<select className={field} value={edit.value.kind} onChange={e => setEdit({ ...edit, value: { ...edit.value, kind: e.target.value } })}><option value="deny">禁止語</option><option value="allow">許可語（重なる禁止語を除外）</option></select></label><label className="text-sm">照合方法<select className={field} value={edit.value.mode} onChange={e => setEdit({ ...edit, value: { ...edit.value, mode: e.target.value } })}>{Object.entries(modes).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label className="text-sm">分類<input className={field} value={edit.value.category} onChange={e => setEdit({ ...edit, value: { ...edit.value, category: e.target.value } })} /></label><label className="text-sm">重要度<input type="number" min={0} max={5} className={field} value={edit.value.severity} onChange={e => setEdit({ ...edit, value: { ...edit.value, severity: e.target.value } })} /></label><label className="text-sm">置換候補（注記）<input className={field} value={edit.value.replacement} onChange={e => setEdit({ ...edit, value: { ...edit.value, replacement: e.target.value } })} /></label><button className={button} disabled={!edit.value.term.trim()} onClick={stageEdit}>変更予定に追加</button><button className={button} onClick={() => setEdit(null)}>閉じる</button></div>}
        {metadata && current && <details className="rounded border p-3"><summary>辞書名・正規化・出典</summary><fieldset disabled={!writable} className="mt-2 grid gap-2 md:grid-cols-2">{["name", "source", "license"].map(k => <label className="text-sm" key={k}>{({ name: "辞書名", source: "出典", license: "ライセンス" } as any)[k]}<input className={field} value={metadata[k]} onChange={e => { setMetadata({ ...metadata, [k]: e.target.value }); setPatchPreview(null); }} /></label>)}<label className="text-sm">正規化<select className={field} value={metadata.normalization.form} onChange={e => { setMetadata({ ...metadata, normalization: { ...metadata.normalization, form: e.target.value } }); setPatchPreview(null); }}><option>NFKC</option><option>NFC</option></select></label><label className="text-sm"><input type="checkbox" checked={metadata.normalization.caseFold !== false} onChange={e => { setMetadata({ ...metadata, normalization: { ...metadata.normalization, caseFold: e.target.checked } }); setPatchPreview(null); }} />大文字小文字を区別しない</label><label className="text-sm">空白<select className={field} value={metadata.normalization.spaces || "preserve"} onChange={e => { setMetadata({ ...metadata, normalization: { ...metadata.normalization, spaces: e.target.value } }); setPatchPreview(null); }}><option value="preserve">維持</option><option value="collapse">連続を1つに</option><option value="remove">削除</option></select></label></fieldset></details>}
        {current && writable && <div className="space-y-2"><p className="text-sm">語の変更予定: {operations.length}件</p><div className="flex gap-2"><button className={button} disabled={busy || !!edit} onClick={() => void task(() => patch(false))}>差分・競合を確認</button><button className={button} disabled={busy || !!edit || !patchPreview || patchPreview.conflictCount > 0} onClick={() => void task(() => patch(true))}>新しい版として保存</button><button className={button} disabled={busy} onClick={() => void task(() => read(selected))}>変更を取り消す</button></div>{patchPreview && <pre className="max-h-44 overflow-auto whitespace-pre-wrap rounded bg-muted p-2 text-xs">{JSON.stringify({ ...patchPreview.diff, duplicateCount: patchPreview.duplicateCount, conflicts: patchPreview.conflicts }, null, 2)}</pre>}</div>}
        {versions.length > 0 && <div className="space-y-2 rounded border p-3">{versions.map(v => <div key={v.revision} className="flex flex-wrap items-center gap-2 text-sm"><span>版 {v.revision} / {v.entryCount.toLocaleString()}語 / {new Date(v.createdAtMs).toLocaleString()}</span><button className={button} onClick={() => { if (guardUnsaved()) void task(() => read(selected, 0, v.revision)); }}>開く</button><button className={button} onClick={() => void task(async () => setDiff(await api(`dictionaries/${selected.id}/diff`, "POST", { from: v.revision, to: page.currentRevision })))}>最新版との差分</button><button className={button} disabled={busy || !writable} onClick={() => { if (confirm(`版 ${v.revision} を新しい版として復元しますか？既存ルールの参照版は変わりません。`)) void task(async () => { const restored = await api(`dictionaries/${selected.id}/restore`, "POST", { revision: v.revision, expectedRevision: page.currentRevision }); await refresh(); await read({ ...selected, revision: restored.revision }); await loadVersions(); }); }}>この内容を復元</button></div>)}{versionCursor && <button className={button} onClick={() => void task(() => loadVersions(versionCursor))}>古い版を取得</button>}{diff && <pre className="max-h-52 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(diff, null, 2)}</pre>}</div>}
        <details className="space-y-2 rounded border p-3"><summary>この版をルールに固定</summary><p className="text-sm text-muted-foreground">表示中の保存済みの版 {page.revision} を、ルールの下書きに割り当てます。通知先と実行中の版は維持します。過去の版は「版の履歴」から開いて選べます。</p><button className={button} onClick={() => void task(() => loadRules())}>割り当て先のルールを取得</button>{rules && <><label className="block text-sm">割り当て先ルール<select className={field} value={ruleId} onChange={e => setRuleId(e.target.value)}><option value="">ルールを選択</option>{rules.filter(r => r.scope !== "guild" || canEdit && selected.scope === "guild").map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{ruleCursor && <button className={button} onClick={() => void task(() => loadRules(ruleCursor))}>ルールの続きを取得</button>}<label className="block text-sm">辞書の差し込み名<input className={field} value={alias} maxLength={64} onChange={e => setAlias(e.target.value)} /></label><button className={button} disabled={busy || dirty || !ruleId || !/^[A-Za-z][A-Za-z0-9_-]{0,63}$/.test(alias) || ["constructor", "prototype"].includes(alias)} onClick={() => void task(pinVersion)}>表示中の版を下書きに固定</button></>}</details>
        <details className="space-y-2 rounded border p-3"><summary>この版で照合テスト（実送信なし）</summary><textarea aria-label="辞書のテスト文" className={`${field} h-24`} value={testText} onChange={e => setTestText(e.target.value)} /><button className={button} disabled={busy} onClick={() => void task(async () => setMatches(await api(`dictionaries/${selected.id}/test`, "POST", { revision: page.revision, text: testText })))}>照合する</button>{matches && <pre className="whitespace-pre-wrap text-xs">{JSON.stringify(matches, null, 2)}</pre>}</details>
        <button className={`${button} text-destructive`} disabled={busy || !writable} onClick={() => { if (confirm("この辞書を削除しますか？過去の版は実行済みルールの記録用に残ります。")) void task(async () => { await api(`dictionaries/${selected.id}`, "DELETE", { expectedRevision: page.currentRevision }); setSelected(null); setPage(null); setMoreDictionaries([]); await refresh(); }); }}>辞書を削除</button>
      </div>}
    </section>
  </fieldset>;
}
