"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import type { AutomationApi } from "./rule-editor";
const field = "w-full rounded border bg-background px-3 py-2 text-sm";
const button = "rounded border bg-background px-3 py-2 text-sm hover:bg-muted disabled:opacity-40";
const statuses: Record<string, string> = { active: "公開中", pending: "旧版の未完了処理", rejected: "機械チェックで拒否", draft: "自分だけの下書き", withdrawn: "公開停止", revoked: "安全上の理由で停止", superseded: "新しい版あり" };
function download(data: any) { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = "automation-package.json"; a.click(); URL.revokeObjectURL(url); }
const blank = { title: "", description: "", category: "general", visibility: "private", license: "", changelog: "", rightsConfirmed: false };

export function MarketplaceManager({ api, scope, canEdit, rules, dictionaries, currentRuleId, refresh, openRule }: { api: AutomationApi; scope: string; canEdit: boolean; rules: any[]; dictionaries: any[]; currentRuleId?: string; refresh: () => Promise<void>; openRule: (id: string) => Promise<void> }) {
  const [items, setItems] = useState<any[]>([]), [cursor, setCursor] = useState<string | null>(null), [search, setSearch] = useState(""), [filter, setFilter] = useState("all"), [pack, setPack] = useState<any>(null), [canModerate, setCanModerate] = useState(false);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState(""), [shareKey, setShareKey] = useState(""), [openId, setOpenId] = useState(""), [versions, setVersions] = useState<any[]>([]), [versionCursor, setVersionCursor] = useState<number | null>(null);
  const [form, setForm] = useState<any>(blank), [editing, setEditing] = useState<any>(null), [sourceType, setSourceType] = useState("workflow"), [sourceId, setSourceId] = useState(currentRuleId || ""), [editingBundle, setEditingBundle] = useState<any>(null);
  const [installed, setInstalled] = useState<any[]>([]), [installedKind, setInstalledKind] = useState("workflow"), [installedCursor, setInstalledCursor] = useState<string | null>(null), [updateTarget, setUpdateTarget] = useState<any>(null), [updateVersion, setUpdateVersion] = useState(1), [updateShareKey, setUpdateShareKey] = useState(""), [updatePreview, setUpdatePreview] = useState<any>(null), [replaceLocal, setReplaceLocal] = useState(false);
  const [review, setReview] = useState<any>(null), [reviewNote, setReviewNote] = useState(""), [report, setReport] = useState(""), [starter, setStarter] = useState<any>(null), [language, setLanguage] = useState("all"), [moderation, setModeration] = useState<any>(null);
  const errorRef = useRef<HTMLParagraphElement>(null);
  useEffect(() => { if (error) errorRef.current?.focus(); }, [error]);
  const changeForm = (patch: Partial<typeof blank>) => setForm((current: typeof blank) => ({ ...current, ...patch, rightsConfirmed: false }));
  const task = async (work: () => Promise<void>) => { setBusy(true); setError(""); setNotice(""); try { await work(); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const load = useCallback(async (after?: string) => {
    const result = await api(`marketplace?search=${encodeURIComponent(search)}&${filter === "all" ? "" : `${filter}=1`}${after ? `&afterId=${after}` : ""}`);
    setItems(old => after ? [...old, ...result.items] : result.items); setCursor(result.nextCursor); setCanModerate(result.canModerate === true);
  }, [api, search, filter]);
  useEffect(() => { let live = true; api("marketplace").then(result => { if (live) { setItems(result.items); setCursor(result.nextCursor); setCanModerate(result.canModerate === true); } }).catch(e => live && setError(e.message)); api("starter").then(result => live && setStarter(result)).catch(e => live && setError(e.message)); return () => { live = false; }; }, [api]);
  async function open(id: string, version?: number, key = shareKey) {
    const result = await api(`marketplace/${id}/open`, "POST", { version, shareKey: key || undefined });
    setPack(result); setOpenId(id); setShareKey(result.packageVisibility === "unlisted" || result.visibility === "unlisted" ? result.shareKey || key : ""); setReviewNote(""); setVersions([]); setReport("");
  }
  useEffect(() => { const fragment = new URLSearchParams(window.location.hash.slice(1)); const id = fragment.get("automation-package"), key = fragment.get("key") || ""; if (id) { setOpenId(id); setShareKey(key); void open(id, undefined, key).catch(e => setError(e.message)); } }, [api]);
  async function versionsLoad(before?: number) { const result = await api(`marketplace/${pack.id}/versions`, "POST", { shareKey: shareKey || pack.shareKey, before }); setVersions(old => before ? [...old, ...result.items] : result.items); setVersionCursor(result.nextVersion); }
  async function feedback(kind: string, extra: any) { await api(`marketplace/${pack.id}/feedback`, "POST", { kind, ...extra, shareKey: shareKey || pack.shareKey }); await open(pack.id, pack.version, shareKey || pack.shareKey); }
  async function savePackage() {
    if (form.visibility !== "private" && (!form.rightsConfirmed || !form.license.trim())) throw new Error("ライセンスを指定し、内容・権利・公開先の確認欄にチェックしてください。");
    let bundle;
    if (sourceType === "current") { if (!editingBundle) throw new Error("編集対象のパッケージを選んでください。"); bundle = editingBundle; }
    else if (sourceType === "workflow") { if (!sourceId) throw new Error("保存済みのルールを選んでください。"); bundle = await api(`workflows/${sourceId}/export`); }
    else { if (!sourceId) throw new Error("辞書を選んでください。"); const data = await api(`dictionaries/${sourceId}/export?format=json`); bundle = { schemaVersion: 1, kind: "dictionary", dictionaries: { words: JSON.parse(data.text) } }; }
    bundle = { ...bundle, license: form.license };
    const saved = await api(`marketplace${editing ? `/${editing.id}` : ""}`, editing ? "PATCH" : "POST", { ...form, bundle, expectedVersion: editing?.latest_version });
    await open(saved.id, saved.version); await load(); setEditing(null); setEditingBundle(null); setSourceType("workflow"); setSourceId(""); setForm(blank); setNotice(saved.status === "active" ? form.visibility === "unlisted" ? "機械チェックを通過し、限定共有を開始しました。共有リンクを知る人が利用できます。" : "機械チェックを通過し、公開しました。共有ルールの一覧から利用できます。" : "非公開の下書きを保存しました。");
  }
  async function installedLoad(kind = installedKind, after?: string) { const result = await api(`installations?kind=${kind}${after ? `&afterId=${after}` : ""}`); setInstalled(old => after ? [...old, ...result.items] : result.items); setInstalledCursor(result.nextCursor); }
  const updateInput = () => ({ workflowId: updateTarget?.workflowId, installId: updateTarget?.installId, version: Number(updateVersion), shareKey: updateShareKey || undefined });
  async function updatePlan() { setUpdatePreview(await api(`marketplace/${updateTarget.packageId}/update-preview`, "POST", updateInput())); setReplaceLocal(false); }
  async function applyUpdate() { await api(`marketplace/${updateTarget.packageId}/update`, "POST", { ...updateInput(), expectedToken: updatePreview.token, replaceLocalChanges: replaceLocal }); await refresh(); await installedLoad(); setUpdatePreview(null); setNotice("選んだ版へ更新しました。ルールは下書きだけ更新し、実行中の版・通知先は変更していません。辞書だけの更新も既存ルールの参照版は変えません。"); }
  async function reviewLoad() { setReview(await api("review")); }
  return <fieldset disabled={busy} className="min-w-0 space-y-4">
    {error && <p ref={errorRef} tabIndex={-1} role="alert" className="rounded border border-destructive p-3 text-sm text-destructive">{error}</p>}{notice && <p role="status" className="rounded border p-3 text-sm">{notice}</p>}
    <section className="space-y-3 rounded border bg-card p-4"><h2 className="font-semibold">無料ルール・辞書マーケットプレイス</h2><p className="text-sm text-muted-foreground">導入した版は固定され、自動で置き換わりません。通知先やWebhookの秘密情報は共有しません。</p>
      <div className="flex flex-wrap gap-2"><input aria-label="共有ルールを検索" className={field + " max-w-lg"} value={search} onChange={e => setSearch(e.target.value)} /><select className={field + " max-w-44"} aria-label="共有ルールの表示範囲" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">公開＋自分の作品</option><option value="mine">自分の作品</option><option value="favorites">お気に入り</option><option value="following">フォロー中の作者</option></select><button className={button} disabled={busy} onClick={() => void task(() => load())}>検索</button></div>
      <div className="grid gap-3 md:grid-cols-3">{items.map(row => <button key={row.id} className="space-y-1 rounded border p-3 text-left" onClick={() => void task(() => open(row.id, undefined, row.shareKey || ""))}><h3 className="font-semibold">{row.title}</h3><p className="line-clamp-3 text-sm">{row.description}</p><p className="text-xs">{row.kind} / v{row.latest_version} / {statuses[row.status] || row.status}</p>{row.publishedVersion && row.publishedVersion !== row.latest_version && <p className="text-xs">利用者へ公開中: v{row.publishedVersion}</p>}</button>)}</div>{!items.length && <p className="text-sm">該当するパッケージはありません。</p>}{cursor && <button className={button} disabled={busy} onClick={() => void task(() => load(cursor))}>続きを取得</button>}
      <details className="space-y-2 rounded border p-3"><summary>限定共有を開く</summary><label className="block text-sm">パッケージID<input className={field} value={openId} onChange={e => setOpenId(e.target.value)} /></label><label className="block text-sm">共有キー<input type="password" autoComplete="off" className={field} value={shareKey} onChange={e => setShareKey(e.target.value)} /></label><button className={button} disabled={busy || !openId} onClick={() => void task(() => open(openId))}>開く</button></details>
    </section>
    {pack && <section className="space-y-3 rounded border bg-card p-4"><h2 className="font-semibold">{pack.title} / v{pack.version}</h2><p className="whitespace-pre-wrap text-sm">{pack.description}</p><p className="text-xs">{statuses[pack.status] || pack.status} / 作者 {pack.owner_user_id} / 導入 {pack.installs || 0} / 評価 {pack.rating ?? "未評価"}</p><p className="text-sm">ライセンス: {pack.bundle.license || "未指定"}</p><p className="text-xs">辞書: {Object.entries(pack.bundle.dictionaries).map(([alias, d]: any) => `${alias}: ${d.entries.length.toLocaleString()}語 / ${d.license || "未指定"}`).join("、") || "なし"}</p>
      {pack.changelog && <p className="whitespace-pre-wrap rounded bg-muted p-2 text-sm">変更内容: {pack.changelog}</p>}{pack.reviewNote && <p className="text-sm">チェック結果: {pack.reviewNote}</p>}
      {pack.canModerate && pack.visibility !== "private" && pack.packageStatus !== "revoked" && <details className="rounded border border-destructive p-3"><summary className="text-sm">安全上の理由で配布・実行を停止</summary><label className="block text-sm">停止理由<textarea className={field} maxLength={4000} value={reviewNote} onChange={e => setReviewNote(e.target.value)} /></label><button className={button} disabled={busy || !reviewNote.trim()} onClick={() => { if (confirm("導入済みルールと未送信の通知も停止します。既に送信が始まった通知は取り消せない場合があります。実行しますか？")) void task(async () => { await api(`marketplace/${pack.id}/status`, "POST", { status: "revoked", note: reviewNote, expectedVersion: pack.latest_version }); await open(pack.id); await load(); setNotice("安全上の停止を適用しました。"); }); }}>配布・実行を停止</button></details>}
      <div className="flex flex-wrap gap-2"><button className={button} disabled={busy || pack.status !== "active" || pack.packageVisibility === "private" || ["withdrawn", "revoked"].includes(pack.packageStatus) || scope === "guild" && !canEdit} onClick={() => void task(async () => { const result = await api(`marketplace/${pack.id}/install`, "POST", { version: pack.version, scope, shareKey: shareKey || pack.shareKey }); await refresh(); setNotice(result.workflow ? "選択した版を導入しました。ルールは下書きなので、通知先を確認してから適用してください。" : "選択した版の辞書を導入しました。辞書画面で確認し、ルールに割り当てて利用できます。"); if (result.workflow) await openRule(result.workflow.id); })}>この版を導入（下書き）</button><button className={button} onClick={() => download(pack.bundle)}>ダウンロード</button><button className={button} disabled={busy || !pack.bundle.license} onClick={() => void task(async () => { const result = await api(`marketplace/${pack.id}/fork`, "POST", { version: pack.version, shareKey: shareKey || pack.shareKey }); await open(result.id); await load(); setNotice("出典とライセンスを引き継いで、非公開のフォークを作成しました。"); })}>フォーク</button><button className={button} disabled={busy} onClick={() => void task(() => feedback("favorite", { enabled: !pack.feedback?.favorite?.enabled }))}>{pack.feedback?.favorite?.enabled ? "お気に入り解除" : "お気に入り"}</button><button className={button} disabled={busy} onClick={() => void task(() => feedback("follow", { enabled: !pack.following }))}>{pack.following ? "作者のフォロー解除" : "作者をフォロー"}</button><button className={button} disabled={busy} onClick={() => void task(() => versionsLoad())}>版を選ぶ</button></div>
      <div className="flex flex-wrap gap-2 text-sm"><span>評価:</span>{[1, 2, 3, 4, 5].map(rating => <button key={rating} className={`${button} ${pack.feedback?.rating?.rating === rating ? "bg-muted" : ""}`} disabled={busy} onClick={() => void task(() => feedback("rating", { rating }))}>{rating}★</button>)}</div>
      {versions.length > 0 && <div className="flex flex-wrap gap-2">{versions.map(v => <button key={v.version} className={button} onClick={() => void task(() => open(pack.id, v.version, shareKey || pack.shareKey))}>v{v.version} / {statuses[v.status] || v.status}</button>)}{versionCursor && <button className={button} onClick={() => void task(() => versionsLoad(versionCursor))}>古い版</button>}</div>}
      {pack.mine && <div className="flex flex-wrap gap-2"><button className={button} onClick={() => { setEditing(pack); setEditingBundle(pack.bundle); setSourceType("current"); setForm({ title: pack.title, description: pack.description, category: pack.category, visibility: pack.visibility, license: pack.bundle.license || "", changelog: "", rightsConfirmed: false }); }}>新しい版を作る</button><button className={button} disabled={busy} onClick={() => void task(async () => { const local = await api("import", "POST", { bundle: pack.bundle, scope }); await refresh(); if (local.workflow) await openRule(local.workflow.id); else setNotice("自分用の辞書として取り込みました。"); })}>内容を自分の編集用に取り込む</button><button className={button} disabled={busy} onClick={() => { if (confirm("パッケージの公開を停止しますか？導入済みのコピーは残ります。")) void task(async () => { await api(`marketplace/${pack.id}/status`, "POST", { status: "withdrawn", expectedVersion: pack.latest_version }); await load(); setPack(null); }); }}>公開を停止</button></div>}
      {pack.mine && pack.visibility === "unlisted" && <label className="block text-sm">限定共有リンク（共有キーを含みます）<input readOnly className={field} value={`${typeof window === "undefined" ? "" : window.location.origin}/dashboard/automation#automation-package=${pack.id}&key=${pack.shareKey}`} /></label>}
      <details className="space-y-2 rounded border p-3"><summary>問題を通報</summary><textarea aria-label="通報理由" className={field} value={report} onChange={e => setReport(e.target.value)} maxLength={2000} /><button className={button} disabled={busy || !report.trim()} onClick={() => void task(async () => { await feedback("report", { reason: report }); setReport(""); setNotice("通報を受け付けました。"); })}>通報する</button></details>
    </section>}
    <details className="space-y-3 rounded border bg-card p-4" open={!!editing}>
      <summary className="font-semibold">{editing ? `「${editing.title}」の新しい版` : "自分のルール・辞書を共有"}</summary>
      <p className="text-sm text-muted-foreground">保存時に機械チェックを通過すると、公開・限定共有はすぐに開始されます。内容・権利・公開先の最終判断は公開者が行ってください。</p>
      <p className="text-xs text-muted-foreground">機械チェックは文脈や画像・音声・動画の意味を判定せず、適法性や安全性を保証しません。この確認で運営の責務が免除されることはありません。</p>
      <fieldset disabled={busy} className="min-w-0 space-y-3">
        <div className="grid gap-2 md:grid-cols-2">
          <label className="text-sm">共有する内容<select className={field} value={sourceType} onChange={e => { setSourceType(e.target.value); setSourceId(""); changeForm({}); }}><option value="workflow">保存済みルール</option><option value="dictionary">辞書パック</option>{editingBundle && <option value="current">編集対象パッケージの内容</option>}</select></label>
          {sourceType !== "current" && <label className="text-sm">対象<select className={field} value={sourceId} onChange={e => { setSourceId(e.target.value); changeForm({}); }}><option value="">選択してください</option>{(sourceType === "workflow" ? rules : dictionaries).map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}
          {[["title", "名称", 120], ["category", "カテゴリ", 64], ["license", "ライセンス（例: CC-BY-4.0 / MIT）", 8000]].map(([key, label, limit]) => <label className="text-sm" key={key}>{label}<input className={field} maxLength={Number(limit)} value={form[key]} onChange={e => changeForm({ [key]: e.target.value })} /></label>)}
          <label className="text-sm">公開範囲<select className={field} value={form.visibility} onChange={e => changeForm({ visibility: e.target.value })}><option value="private">自分だけ</option><option value="unlisted">限定共有</option><option value="public">公開</option></select></label>
        </div>
        {[["description", "説明", 8000], ["changelog", "変更内容", 4000]].map(([key, label, limit]) => <label key={key} className="block text-sm">{label}<textarea className={field} maxLength={Number(limit)} value={form[key]} onChange={e => changeForm({ [key]: e.target.value })} /></label>)}
        <p className="text-sm">{form.visibility === "private" ? "自分だけが使う下書きとして保存します。" : form.visibility === "unlisted" ? "保存後すぐに、共有リンクを知る人が利用できます。" : "保存後すぐに、共有ルールの一覧から利用できます。"}</p>
        {form.visibility !== "private" && <><p className="text-xs text-muted-foreground">対象・名称・ライセンスを指定し、確認欄にチェックしてください。内容や公開範囲を変えた場合は再確認が必要です。</p><label className="flex items-start gap-2 text-sm"><input className="mt-1 shrink-0" type="checkbox" checked={form.rightsConfirmed} onChange={e => setForm({ ...form, rightsConfirmed: e.target.checked })} />内容・再配布する権利・公開先を自分の責任で確認しました。機械チェックの限界を理解しています。</label></>}
        <div className="flex flex-wrap gap-2"><button className={button} disabled={busy || !form.title.trim() || sourceType !== "current" && !sourceId || form.visibility !== "private" && (!form.rightsConfirmed || !form.license.trim())} onClick={() => void task(savePackage)}>{form.visibility === "private" ? "非公開で保存" : form.visibility === "unlisted" ? "保存して限定共有" : "保存して公開"}</button>{editing && <button className={button} onClick={() => { setEditing(null); setEditingBundle(null); setForm(blank); setSourceType("workflow"); setSourceId(""); }}>新規作成へ戻す</button>}</div>
      </fieldset>
    </details>
    <details className="space-y-3 rounded border bg-card p-4"><summary className="font-semibold">導入済みパッケージと更新</summary><div className="flex gap-2"><select className={field + " max-w-48"} value={installedKind} onChange={e => { setInstalledKind(e.target.value); setInstalled([]); setInstalledCursor(null); setUpdateTarget(null); setUpdatePreview(null); setReplaceLocal(false); setUpdateShareKey(""); }}><option value="workflow">ルール</option><option value="dictionary">辞書</option></select><button className={button} disabled={busy} onClick={() => void task(() => installedLoad())}>一覧を取得</button></div>{installed.map(item => <div key={item.workflowId || item.installId} className="flex flex-wrap items-center gap-2 rounded border p-2 text-sm"><span>{item.name} / 固定版 {item.version} / 公開版 {item.availableVersion}</span><button className={button} disabled={busy || item.scope === "guild" && !canEdit} onClick={() => { setUpdateTarget(item); setUpdateVersion(item.availableVersion); setUpdatePreview(null); setReplaceLocal(false); setUpdateShareKey(pack?.id === item.packageId ? shareKey || pack.shareKey || "" : ""); }}>更新する版を選ぶ</button>{item.workflowId && <button className={button} onClick={() => void task(() => openRule(item.workflowId))}>ルールを開く</button>}</div>)}{installedCursor && <button className={button} onClick={() => void task(() => installedLoad(installedKind, installedCursor))}>続きを取得</button>}
      {updateTarget && <div className="space-y-2 rounded border p-3"><p className="text-sm">{updateTarget.name} の更新（実行中のルールは変更しません）</p><label className="block text-sm">更新先の版<input type="number" min={1} className={field} value={updateVersion} onChange={e => { setUpdateVersion(Number(e.target.value)); setUpdatePreview(null); }} /></label><label className="block text-sm">限定共有の更新キー（必要な場合）<input type="password" autoComplete="off" className={field} value={updateShareKey} onChange={e => { setUpdateShareKey(e.target.value); setUpdatePreview(null); setReplaceLocal(false); }} /></label><button className={button} disabled={busy} onClick={() => void task(updatePlan)}>更新差分を確認</button>{updatePreview && <><p className="text-sm">v{updatePreview.fromVersion} → v{updatePreview.toVersion} / {updatePreview.localChanges ? "ローカル編集あり" : "ローカル編集なし"}</p><pre className="max-h-48 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(updatePreview.dictionaryDiffs, null, 2)}</pre>{updatePreview.workflowPreview && <details><summary>更新前・更新後のルール</summary><div className="grid gap-2 md:grid-cols-2"><pre className="max-h-64 overflow-auto text-xs">{JSON.stringify(updatePreview.previousWorkflow, null, 2)}</pre><pre className="max-h-64 overflow-auto text-xs">{JSON.stringify(updatePreview.workflowPreview, null, 2)}</pre></div></details>}{updatePreview.localChanges && <label className="block text-sm"><input type="checkbox" checked={replaceLocal} onChange={e => setReplaceLocal(e.target.checked)} />ローカルの編集内容をこの版で置き換えることを確認しました。</label>}<button className={button} disabled={busy || updatePreview.localChanges && !replaceLocal} onClick={() => void task(applyUpdate)}>この版へ更新</button></>}</div>}
    </details>
    {starter && <details className="space-y-3 rounded border bg-card p-4"><summary className="font-semibold">禁止語スターター辞書（{starter.uniqueEntries.toLocaleString()}語）</summary><p className="text-sm">{starter.source}</p><p className="text-xs text-muted-foreground">{starter.caveat}</p><p className="text-sm">{starter.license}</p><select className={field} aria-label="スターター辞書の言語" value={language} onChange={e => setLanguage(e.target.value)}><option value="all">全言語（重複除去済み）</option>{starter.languages.map((l: any) => <option value={l.id} key={l.id}>{l.id} / {l.entryCount}語</option>)}</select><button className={button} disabled={busy || scope === "guild" && !canEdit} onClick={() => void task(async () => { await api("starter", "POST", { language, scope }); await refresh(); setNotice("出典・ライセンス付きのスターター辞書を追加しました。辞書画面で例外や用途に合わせて編集できます。"); })}>自分の辞書へ取り込む</button></details>}
    {canModerate && <details className="space-y-3 rounded border bg-card p-4"><summary className="font-semibold">例外対応・共通辞書</summary><div className="flex gap-2"><button className={button} disabled={busy} onClick={() => void task(reviewLoad)}>通報を取得</button><button className={button} disabled={busy} onClick={() => void task(async () => setModeration(await api("moderation")))}>共通辞書の設定</button></div>{review?.reports.map((r: any) => <div className="rounded border p-3 text-sm" key={r.id}><p>{r.value.reason}</p><div className="mt-2 flex gap-2"><button className={button} onClick={() => void task(() => open(r.subject_id, undefined, ""))}>対象を確認</button><button className={button} onClick={() => void task(async () => { await api(`reports/${r.id}`, "POST", { note: "確認済み" }); await reviewLoad(); })}>対応済みにする</button></div></div>)}{moderation && <div className="space-y-2 rounded border p-3"><label className="block text-sm"><input type="checkbox" checked={moderation.useStarter} onChange={e => setModeration({ ...moderation, useStarter: e.target.checked })} />スターターを併用</label><label className="block text-sm">追加の禁止語・許可語辞書<select className={field} value={moderation.dictionaryId || ""} onChange={e => { const d = dictionaries.find(d => d.id === e.target.value); setModeration({ ...moderation, dictionaryId: d?.id || null, dictionaryRevision: d?.revision || null }); }}><option value="">追加なし</option>{dictionaries.map(d => <option key={d.id} value={d.id}>{d.name} / 最新v{d.revision}</option>)}</select></label>{moderation.dictionaryId && <label className="block text-sm">固定する版<input type="number" min={1} className={field} value={moderation.dictionaryRevision} onChange={e => setModeration({ ...moderation, dictionaryRevision: Number(e.target.value) })} /></label>}<button className={button} disabled={busy} onClick={() => void task(async () => { await api("moderation", "POST", { ...moderation, expectedRevision: moderation.revision }); setModeration(await api("moderation")); setNotice("共通辞書の版を更新しました。"); })}>辞書設定を保存</button></div>}</details>}
  </fieldset>;
}
