'use strict';

const EMBED_COLOR = 0xE4405F;
const MAX_MEDIA_PER_MESSAGE = 10;
const DESCRIPTION_MAX_LENGTH = 3500;
const CAPTION_MAX_LENGTH = 3000;
const CACHE_TTL_MS = 30 * 60 * 1000;
const PROFILE_API_RATE_LIMIT_BACKOFF_MS = 10 * 60 * 1000;

module.exports = {
    EMBED_COLOR,
    MAX_MEDIA_PER_MESSAGE,
    DESCRIPTION_MAX_LENGTH,
    CAPTION_MAX_LENGTH,
    CACHE_TTL_MS,
    PROFILE_API_RATE_LIMIT_BACKOFF_MS,
};
