'use strict';

// Run only against a fresh automation-ui-harness.js. All mutations below use
// rendered controls; direct API reads verify their persisted results.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { newWorkflow } = require('../src/automation/schema');
const { parseDictionary } = require('../src/automation/dictionary-format');
if (process.env.NODE_ENV !== 'test') throw new Error('NODE_ENV=test is required');
const root = path.resolve(__dirname, '..');
process.env.PLAYWRIGHT_BROWSERS_PATH = path.join(root, 'node_modules/.cache/ux-browser');
const { chromium } = require('../design-previews/qa/node_modules/playwright');
const { expect } = require('../design-previews/qa/node_modules/playwright/test');
const fixture = new URL(process.env.AUTOMATION_AUDIT_UI_URL || '');
if (fixture.hostname !== '127.0.0.1' || fixture.protocol !== 'http:' || !fixture.port) throw new Error('Explicit loopback fixture required');
const folder = path.join(root, 'docs/audits/completion/sharing');
fs.mkdirSync(folder, { recursive: true });

async function main() {
    const browser = await chromium.launch({ headless: true });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: 'ja-JP', serviceWorkers: 'block' });
    const result = { at: new Date().toISOString(), fixtureOnly: true, realMessages: 0, checks: [], pageErrors: [], blockedRequests: [], requests: [], limitations: ['Harness uses a fixed fixture actor; cross-user access, role checks and transaction rollback are verified separately by real SQL tests.', 'Million-row throughput is covered by the separate benchmark, not by loading a million DOM rows.', 'No production authentication, production DB, deployment or Discord delivery is exercised.'] };
    await context.route('**/*', route => {
        if (new URL(route.request().url()).origin === fixture.origin) return route.continue();
        result.blockedRequests.push(route.request().url()); return route.abort();
    });
    const page = await context.newPage();
    page.setDefaultTimeout(15000);
    page.on('pageerror', error => result.pageErrors.push(error.stack));
    page.on('response', response => {
        const url = new URL(response.url());
        if (url.pathname.startsWith('/api/automation/')) result.requests.push({ method: response.request().method(), path: url.pathname, status: response.status() });
    });
    let acceptDialog = true, confirmations = 0;
    page.on('dialog', async dialog => { confirmations++; await (acceptDialog ? dialog.accept() : dialog.dismiss()); });
    const checked = name => { assert.deepEqual(result.pageErrors, []); result.checks.push(name); console.log(`PASS ${name}`); };
    const button = name => page.getByRole('button', { name, exact: true });
    const read = async route => {
        const response = await context.request.get(`${fixture.origin}/api/automation/${route}`);
        assert.equal(response.ok(), true, await response.text()); return response.json();
    };
    const mutation = async (route, method, action) => {
        const response = page.waitForResponse(r => new URL(r.url()).pathname === `/api/automation/${route}` && r.request().method() === method);
        const [received] = await Promise.all([response, action()]); const body = await received.json();
        assert.equal(received.ok(), true, JSON.stringify(body)); return body;
    };
    const tab = async name => {
        if (await button('ルール一覧へ').isVisible()) await button('ルール一覧へ').click();
        await page.getByRole('navigation', { name: '通知メニュー' }).getByRole('button', { name, exact: true }).click();
    };
    const details = text => page.locator('details').filter({ has: page.locator('summary').filter({ hasText: text }) }).last();
    const expand = async text => { const node = details(text); if (!(await node.getAttribute('open'))) { if (!(await node.evaluate(el => el.open))) await node.locator('summary').first().click(); } return node; };
    const upload = async (name, format, text) => {
        const form = await expand('辞書の一括取り込み');
        await form.getByRole('textbox', { name: '辞書名', exact: true }).fill(name);
        await form.getByRole('textbox', { name: '出典', exact: true }).fill('自作の架空試験データ');
        await form.getByRole('textbox', { name: '利用条件・ライセンス', exact: true }).fill('CC0-1.0');
        await page.getByLabel('辞書ファイル', { exact: true }).setInputFiles({ name: `${name}.${format}`, mimeType: 'text/plain', buffer: Buffer.from(text) });
        const preview = await mutation('dictionary-preview', 'POST', () => button('取り込み内容を確認').click());
        const saved = await mutation('dictionaries', 'POST', () => button('新しい辞書として保存').click());
        await page.getByRole('heading', { name: new RegExp(`${name} / 表示版 1`) }).waitFor();
        return { ...saved, preview };
    };
    const openDictionary = async (id, name) => {
        await tab('辞書');
        const row = await read(`dictionaries/${id}`);
        await page.locator(`button[data-dictionary-id="${id}"]`).click();
        await page.getByRole('heading', { name: new RegExp(`${name || row.name} / 表示版`) }).waitFor();
    };
    const addTerm = async (id, term) => {
        await button('語を追加').click();
        await page.getByRole('textbox', { name: '語', exact: true }).fill(term);
        await button('変更予定に追加').click();
        const preview = await mutation(`dictionaries/${id}/patch`, 'POST', () => button('差分・競合を確認').click());
        const saved = await mutation(`dictionaries/${id}/patch`, 'POST', () => button('新しい版として保存').click());
        await expect(button('差分・競合を確認')).toBeEnabled();
        return { preview, saved };
    };
    const download = async (label, name) => {
        const pending = page.waitForEvent('download'); await button(label).click(); const file = await pending;
        await file.saveAs(path.join(folder, name)); return fs.readFileSync(path.join(folder, name), 'utf8');
    };
    const saveRule = async id => {
        await expect(button('下書きを保存')).toBeEnabled();
        await mutation(`workflows/${id}`, 'PATCH', () => button('下書きを保存').click());
        await expect(button('下書きを保存')).toBeEnabled();
    };
    const publish = async ({ title, sourceType = 'workflow', sourceId, visibility = 'public', editingId }) => {
        const form = await expand(editingId ? 'の新しい版' : '自分のルール・辞書を共有');
        if (sourceId) { await form.getByRole('combobox', { name: '共有する内容', exact: true }).selectOption(sourceType); await form.getByRole('combobox', { name: '対象', exact: true }).selectOption(sourceId); }
        await form.getByRole('textbox', { name: '名称', exact: true }).fill(title);
        await form.getByRole('textbox', { name: 'ライセンス（例: CC-BY-4.0 / MIT）', exact: true }).fill('CC0-1.0');
        await form.getByRole('combobox', { name: '公開範囲', exact: true }).selectOption(visibility);
        if (visibility !== 'private') await form.getByRole('checkbox', { name: /内容・再配布する権利/ }).check();
        const saved = await mutation(`marketplace${editingId ? `/${editingId}` : ''}`, editingId ? 'PATCH' : 'POST', () => form.getByRole('button', { name: visibility === 'private' ? '非公開で保存' : visibility === 'unlisted' ? '保存して限定共有' : '保存して公開', exact: true }).click());
        await page.getByRole('heading', { name: `${title} / v${saved.version}`, exact: true }).waitFor();
        assert.equal(saved.status, visibility === 'private' ? 'draft' : 'active'); return saved;
    };
    const openPack = async (id, key = '') => {
        await tab('共有ルール');
        const form = await expand('限定共有を開く');
        await form.getByRole('textbox', { name: 'パッケージID', exact: true }).fill(id);
        await form.getByLabel('共有キー', { exact: true }).fill(key);
        await mutation(`marketplace/${id}/open`, 'POST', () => form.getByRole('button', { name: '開く', exact: true }).click());
        await expect(button('版を選ぶ')).toBeEnabled();
    };
    const install = async id => {
        const installed = await mutation(`marketplace/${id}/install`, 'POST', () => button('この版を導入（下書き）').click());
        if (installed.workflow) await button('ルール一覧へ').waitFor();
        else await expect(button('この版を導入（下書き）')).toBeEnabled();
        return installed;
    };
    try {
        await page.goto(fixture.href);
        await tab('辞書');
        const txt = await upload('UI TXT 辞書', 'txt', '広告\r\nお知らせ\r\n広告\r\n');
        assert.equal(txt.preview.entryCount, 2); assert.equal(txt.preview.duplicateCount, 1);
        await expand('辞書の一括取り込み');
        await page.getByLabel('辞書ファイル', { exact: true }).setInputFiles({ name: 'conflict.csv', mimeType: 'text/csv', buffer: Buffer.from('term,kind\nSAMPLE,deny\nsample,allow\n') });
        const conflict = await mutation('dictionary-preview', 'POST', () => button('取り込み内容を確認').click());
        assert.equal(conflict.conflictCount, 1); await expect(button('新しい辞書として保存')).toBeDisabled();
        const csv = await upload('UI CSV 辞書', 'csv', 'term,kind,mode,category,severity,replacement\n広告,deny,contains,一般,2,\n広告制作,allow,word,例外,0,\n=1+1,deny,exact,試験,0,\n');
        assert.equal(csv.preview.entryCount, 3);
        await expand('この版で照合テスト');
        await page.getByRole('textbox', { name: '辞書のテスト文', exact: true }).fill('広告');
        assert.equal((await mutation(`dictionaries/${csv.id}/test`, 'POST', () => button('照合する').click())).length, 1);
        await page.getByRole('textbox', { name: '辞書のテスト文', exact: true }).fill('広告制作');
        assert.equal((await mutation(`dictionaries/${csv.id}/test`, 'POST', () => button('照合する').click())).length, 0);
        checked('Conflicting allow/deny import disables saving; UI dictionary test applies the allow exception without sending');
        const data = { schemaVersion: 1, name: 'UI JSON 辞書', source: '自作の架空試験データ', license: 'CC0-1.0', entries: Array.from({ length: 205 }, (_, i) => `word-${i}`) };
        const json = await upload(data.name, 'json', JSON.stringify(data));
        assert.equal(await page.locator('tbody tr').count(), 100);
        await button('次の100語').click(); await page.getByRole('cell', { name: 'word-100', exact: true }).waitFor();
        assert.equal(await page.locator('tbody tr').count(), 100);
        checked('Actual TXT/CSV/JSON file controls import and persist; deduplication and bounded 100-row paging work');

        await page.getByRole('textbox', { name: '辞書の語を検索' }).fill('word-20');
        await button('検索').click(); await page.getByRole('cell', { name: 'word-20', exact: true }).waitFor();
        const row = page.getByRole('row').filter({ has: page.getByRole('cell', { name: 'word-20', exact: true }) });
        await row.getByRole('button', { name: '編集', exact: true }).click();
        await page.getByRole('textbox', { name: '語', exact: true }).fill('word-20-edited');
        await page.getByRole('combobox', { name: '処理', exact: true }).selectOption('allow');
        await button('変更予定に追加').click();
        await page.locator('tbody tr').first().getByRole('button', { name: '編集', exact: true }).click();
        await expect(page.getByRole('textbox', { name: '語', exact: true })).toHaveValue('word-20-edited');
        await expect(button('差分・競合を確認')).toBeDisabled();
        await button('閉じる').click();
        await page.getByRole('row').filter({ has: page.getByRole('cell', { name: 'word-200', exact: true }) }).getByRole('button', { name: '削除予約' }).click();
        const patch = await mutation(`dictionaries/${json.id}/patch`, 'POST', () => button('差分・競合を確認').click());
        assert.equal(patch.diff.removed, 2); assert.equal(patch.diff.added, 1);
        await mutation(`dictionaries/${json.id}/patch`, 'POST', () => button('新しい版として保存').click());
        await page.getByRole('heading', { name: 'UI JSON 辞書 / 表示版 2 / 最新 2', exact: true }).waitFor();
        const exported = JSON.parse(await download('JSON出力', 'dictionary-v2.json'));
        assert.equal(exported.entries[20].term, 'word-20-edited'); assert.equal(exported.entries[20].kind, 'allow');
        assert(!exported.entries.includes('word-200'));
        assert.deepEqual(parseDictionary(await download('CSV出力', 'dictionary-v2.csv'), 'csv'), exported);
        assert((await download('TXT出力', 'dictionary-v2.txt')).includes('word-20-edited'));
        checked('Filtered edit/delete use stable source indices; preview, immutable save and JSON/CSV/TXT downloads agree');

        const metadata = await expand('辞書名・正規化・出典');
        await metadata.getByRole('textbox', { name: '出典', exact: true }).fill('未保存の出典');
        const beforeConfirm = confirmations; acceptDialog = false;
        await page.getByRole('button', { name: 'UI TXT 辞書 / v1 / 2語', exact: true }).click();
        assert.equal(confirmations, beforeConfirm + 1);
        await expect(metadata.getByRole('textbox', { name: '出典', exact: true })).toHaveValue('未保存の出典');
        acceptDialog = true; await button('変更を取り消す').click();
        await button('版の履歴').click();
        const oldVersion = page.locator('div').filter({ has: page.locator('span').filter({ hasText: /^版 1 \/ 205語/ }) }).filter({ has: button('この内容を復元') }).last();
        await oldVersion.getByRole('button', { name: '最新版との差分', exact: true }).click();
        await oldVersion.getByRole('button', { name: '開く', exact: true }).click();
        await page.getByRole('heading', { name: 'UI JSON 辞書 / 表示版 1 / 最新 2', exact: true }).waitFor();
        assert.deepEqual(JSON.parse(await download('JSON出力', 'dictionary-v1.json')), data);
        await oldVersion.getByRole('button', { name: 'この内容を復元', exact: true }).click();
        await page.getByRole('heading', { name: 'UI JSON 辞書 / 表示版 3 / 最新 3', exact: true }).waitFor();
        assert.deepEqual(JSON.parse((await read(`dictionaries/${json.id}/export?revision=3`)).text), data);
        checked('Metadata-only unsaved edits warn; history diff, old-version export and restore preserve immutable revisions');
        const settings = await expand('辞書名・正規化・出典');
        await settings.getByRole('textbox', { name: '出典', exact: true }).fill('更新した自作の出典');
        await settings.getByRole('combobox', { name: '空白', exact: true }).selectOption('collapse');
        const metadataDiff = await mutation(`dictionaries/${json.id}/patch`, 'POST', () => button('差分・競合を確認').click());
        assert(metadataDiff.diff.metadataChanged.includes('source')); assert(metadataDiff.diff.metadataChanged.includes('normalization'));
        await mutation(`dictionaries/${json.id}/patch`, 'POST', () => button('新しい版として保存').click());
        await page.getByRole('heading', { name: 'UI JSON 辞書 / 表示版 4 / 最新 4', exact: true }).waitFor();
        const savedMetadata = JSON.parse((await read(`dictionaries/${json.id}/export`)).text);
        assert.equal(savedMetadata.source, '更新した自作の出典'); assert.equal(savedMetadata.normalization.spaces, 'collapse');
        checked('Metadata and normalization edits are previewed and saved as a new immutable dictionary revision');
        await page.screenshot({ path: path.join(folder, 'dictionary-desktop.png'), fullPage: true });
        await page.setViewportSize({ width: 390, height: 844 });
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
        await page.screenshot({ path: path.join(folder, 'dictionary-mobile.png'), fullPage: true });
        await page.setViewportSize({ width: 1440, height: 1000 });
        await openDictionary(txt.id); await mutation(`dictionaries/${txt.id}`, 'DELETE', () => button('辞書を削除').click());
        assert(!(await read('dictionaries')).items.some(d => d.id === txt.id));
        checked('Dictionary deletion removes the list entry; dictionary layout fits a 390px viewport');

        await tab('通知一覧');
        await expand('通知先の管理'); await button('通知先を追加').click();
        const destinationDialog = page.getByRole('dialog', { name: '通知先を追加', exact: true });
        await destinationDialog.getByRole('textbox', { name: '通知先の名前', exact: true }).fill('UI fixture webhook');
        await destinationDialog.getByRole('combobox', { name: '通知先の種類', exact: true }).selectOption('webhook');
        const secret = 'fixture-only-not-a-real-webhook-aaaaaaaaaaaa';
        await destinationDialog.getByLabel(/^Webhook URL/).fill(`https://discord.com/api/webhooks/555555555555555555/${secret}`);
        const webhook = await mutation('destinations', 'POST', () => destinationDialog.getByRole('button', { name: '通知先を保存', exact: true }).click());
        await destinationDialog.waitFor({ state: 'hidden' });
        assert(!JSON.stringify(await read('destinations')).includes(secret));
        await tab('スタジオ');
        const sourceBundle = { schemaVersion: 1, kind: 'workflow', workflow: newWorkflow('UI dependency workflow'), dictionaries: { words: { schemaVersion: 1, name: 'UI dependency words', source: '自作の架空試験データ', license: 'CC0-1.0', entries: ['one'] } }, license: 'CC0-1.0' };
        const importResponse = page.waitForResponse(r => new URL(r.url()).pathname === '/api/automation/import' && !r.request().postDataJSON()?.preview);
        await page.getByLabel('パッケージをインポート', { exact: true }).setInputFiles({ name: 'source.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(sourceBundle)) });
        const source = await (await importResponse).json(); assert(source.workflow?.id);
        await page.getByRole('textbox', { name: 'ルール名', exact: true }).waitFor();
        const bindings = await expand('辞書・通知先の割り当て');
        await bindings.getByRole('textbox', { name: '差し込み名', exact: true }).fill('default');
        const dm = (await read('destinations')).items.find(d => d.kind === 'dm');
        await bindings.getByRole('combobox', { name: '通知先を割り当て', exact: true }).selectOption(dm.id);
        await bindings.getByRole('textbox', { name: '差し込み名', exact: true }).fill('privateWebhook');
        await bindings.getByRole('combobox', { name: '通知先を割り当て', exact: true }).selectOption(webhook.id);
        await saveRule(source.workflow.id);
        const cleanExport = JSON.parse(await download('共有用エクスポート', 'workflow-export.json'));
        assert(!JSON.stringify(cleanExport).includes(dm.id)); assert(!JSON.stringify(cleanExport).includes(webhook.id)); assert(!JSON.stringify(cleanExport).includes(secret)); assert.equal(cleanExport.bindings, undefined);
        await openDictionary(source.dictionaries.words.id); await addTerm(source.dictionaries.words.id, 'new local dictionary revision');
        assert.equal((await read(`workflows/${source.workflow.id}`)).bindings.dictionaries.words.revision, 1);
        assert.deepEqual((await read(`workflows/${source.workflow.id}/export`)).dictionaries.words.entries, ['one']);
        checked('A UI dictionary edit leaves existing workflow bindings pinned; export of a webhook-bound workflow omits endpoint IDs and the fixture secret');
        await tab('共有ルール');
        const publicPack = await publish({ title: 'UI public workflow', sourceId: source.workflow.id });
        await page.getByRole('textbox', { name: '共有ルールを検索', exact: true }).fill('UI public workflow');
        await button('検索').click(); await page.getByRole('heading', { name: 'UI public workflow', exact: true }).waitFor();
        const installed = await install(publicPack.id); assert(installed.workflow?.id); assert(installed.dictionaries.words?.id);
        assert.equal(installed.workflow.enabled, false); assert.equal(installed.dictionaries.words.revision, 1);
        assert.deepEqual(installed.workflow.bindings.destinations, {});
        await page.getByRole('textbox', { name: 'ルール名', exact: true }).fill('UI local workflow edits');
        const localBindings = await expand('辞書・通知先の割り当て');
        await localBindings.getByRole('textbox', { name: '差し込み名', exact: true }).fill('default');
        await localBindings.getByRole('combobox', { name: '通知先を割り当て', exact: true }).selectOption(dm.id);
        await saveRule(installed.workflow.id);
        checked('Workflow file import, public publication, search and UI installation persist dictionary dependencies and omit destination bindings');

        await openPack(publicPack.id); await button('新しい版を作る').click();
        await publish({ title: 'UI public workflow v2', editingId: publicPack.id });
        assert.equal((await read('installations')).items.find(i => i.workflowId === installed.workflow.id).version, 1);
        const installs = await expand('導入済みパッケージと更新');
        await installs.getByRole('button', { name: '一覧を取得', exact: true }).click();
        await installs.getByRole('button', { name: '更新する版を選ぶ', exact: true }).click();
        const plan = await mutation(`marketplace/${publicPack.id}/update-preview`, 'POST', () => button('更新差分を確認').click());
        assert.equal(plan.localChanges, true); assert.equal(plan.fromVersion, 1); assert.equal(plan.toVersion, 2);
        await expect(button('この版へ更新')).toBeDisabled();
        await page.getByRole('checkbox', { name: 'ローカルの編集内容をこの版で置き換えることを確認しました。', exact: true }).check();
        await mutation(`marketplace/${publicPack.id}/update`, 'POST', () => button('この版へ更新').click());
        const updated = await read(`workflows/${installed.workflow.id}`);
        assert.equal(updated.draft.name, sourceBundle.workflow.name); assert.equal(updated.bindings.destinations.default, dm.id); assert.equal(updated.activeRevision, null);
        checked('Published updates leave installations pinned until preview and explicit local-edit replacement; update preserves destinations and inactive state');
        await installs.getByRole('combobox').selectOption('dictionary');
        await expect(button('更新差分を確認')).toHaveCount(0);
        checked('Changing installation kind clears the previous update target and preview');
        await button('版を選ぶ').click(); await button('v1 / 公開中').click();
        const older = await install(publicPack.id); assert.equal(older.workflow.draft.name, sourceBundle.workflow.name);
        assert.equal((await read('installations')).items.find(i => i.workflowId === older.workflow.id).version, 1);
        checked('Version picker installs an explicitly selected older package revision');

        await tab('共有ルール');
        const dictPack = await publish({ title: 'UI dictionary pack', sourceType: 'dictionary', sourceId: csv.id });
        const dictInstall = await install(dictPack.id); assert(dictInstall.installId);
        await openDictionary(csv.id); await addTerm(csv.id, 'new upstream term');
        await openPack(dictPack.id); await button('新しい版を作る').click();
        await publish({ title: 'UI dictionary pack v2', sourceType: 'dictionary', sourceId: csv.id, editingId: dictPack.id });
        const dictUpdates = await expand('導入済みパッケージと更新');
        await dictUpdates.getByRole('combobox').selectOption('dictionary');
        await dictUpdates.getByRole('button', { name: '一覧を取得', exact: true }).click();
        await dictUpdates.getByRole('button', { name: '更新する版を選ぶ', exact: true }).click();
        const dictPlan = await mutation(`marketplace/${dictPack.id}/update-preview`, 'POST', () => button('更新差分を確認').click());
        assert.equal(dictPlan.dictionaryDiffs[0].added, 1);
        const changed = await mutation(`marketplace/${dictPack.id}/update`, 'POST', () => button('この版へ更新').click());
        assert.equal(changed.dictionaries.words.id, dictInstall.dictionaries.words.id); assert.equal(changed.dictionaries.words.revision, 2);
        checked('Dictionary package UI publish/install/update previews upstream entries and preserves dictionary identity with a new revision');

        await openPack(publicPack.id);
        const fork = await mutation(`marketplace/${publicPack.id}/fork`, 'POST', () => button('フォーク').click());
        await page.getByRole('heading', { name: /のフォーク \/ v1/ }).waitFor();
        const forkData = await read(`marketplace/${fork.id}`);
        assert.equal(forkData.visibility, 'private'); assert.equal(forkData.fork_of, publicPack.id); assert.equal(forkData.bundle.license, 'CC0-1.0');
        await openPack(publicPack.id);
        const report = await expand('問題を通報');
        await report.getByRole('textbox', { name: '通報理由', exact: true }).fill('架空の動作確認用の通報');
        await mutation(`marketplace/${publicPack.id}/feedback`, 'POST', () => report.getByRole('button', { name: '通報する', exact: true }).click());
        assert((await read('review')).reports.some(r => r.subject_id === publicPack.id));
        checked('UI fork retains source/license as private; UI report persists for exceptional handling');

        const limited = await publish({ title: 'UI unlisted workflow', sourceId: source.workflow.id, visibility: 'unlisted' });
        const link = await page.getByLabel('限定共有リンク（共有キーを含みます）', { exact: true }).inputValue();
        const fragment = new URLSearchParams(new URL(link).hash.slice(1)); assert.equal(fragment.get('automation-package'), limited.id); assert.equal(fragment.get('key').length, 64);
        await openPack(limited.id, fragment.get('key')); await install(limited.id);
        await tab('共有ルール');
        const privatePack = await publish({ title: 'UI private workflow', sourceId: source.workflow.id, visibility: 'private' });
        await expect(button('この版を導入（下書き）')).toBeDisabled();
        assert.equal((await read(`marketplace/${privatePack.id}`)).visibility, 'private');
        const publicDownload = await download('ダウンロード', 'package-download.json');
        assert(!publicDownload.includes(fragment.get('key'))); assert(!publicDownload.includes(dm.id)); assert(!publicDownload.includes('fixture-only-not-a-real-webhook'));
        checked('Public/unlisted/private UI publication and limited-share opening work; private drafts cannot be installed and downloads exclude bindings/share keys');
        await page.screenshot({ path: path.join(folder, 'marketplace-desktop.png'), fullPage: true });
        await page.setViewportSize({ width: 390, height: 844 });
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
        await page.screenshot({ path: path.join(folder, 'marketplace-mobile.png'), fullPage: true });
        checked('Marketplace fits a 390px viewport');
        await page.setViewportSize({ width: 1440, height: 1000 });
        await openDictionary(json.id); await button('版の履歴').click();
        const firstRevision = page.locator('div').filter({ has: page.locator('span').filter({ hasText: /^版 1 \/ 205語/ }) }).filter({ has: button('この内容を復元') }).last();
        await firstRevision.getByRole('button', { name: '開く', exact: true }).click();
        await page.getByRole('heading', { name: 'UI JSON 辞書 / 表示版 1 / 最新 4', exact: true }).waitFor();
        const pin = await expand('この版をルールに固定');
        await pin.getByRole('button', { name: '割り当て先のルールを取得', exact: true }).click();
        await pin.getByRole('combobox', { name: '割り当て先ルール', exact: true }).selectOption(source.workflow.id);
        await pin.getByRole('textbox', { name: '辞書の差し込み名', exact: true }).fill('words');
        const beforePin = await read(`workflows/${source.workflow.id}`), beforePinConfirm = confirmations;
        await mutation(`workflows/${source.workflow.id}`, 'PATCH', () => pin.getByRole('button', { name: '表示中の版を下書きに固定', exact: true }).click());
        const pinned = await read(`workflows/${source.workflow.id}`);
        assert.equal(confirmations, beforePinConfirm + 1);
        assert.deepEqual(pinned.bindings.dictionaries.words, { id: json.id, revision: 1 });
        assert.deepEqual(pinned.bindings.destinations, beforePin.bindings.destinations);
        assert.deepEqual(pinned.draft, beforePin.draft); assert.equal(pinned.activeRevision, beforePin.activeRevision);
        assert.equal((await read(`dictionaries/${json.id}`)).currentRevision, 4);
        await page.screenshot({ path: path.join(folder, 'dictionary-version-pin.png'), fullPage: true });
        checked('Arbitrary historical dictionary revision is pinned through rendered controls, with replacement confirmation and unchanged destinations/active revision');
        assert.equal(result.requests.filter(r => r.status >= 400).length, 0, 'all UI requests succeeded');
        assert.deepEqual(result.blockedRequests, []); assert.deepEqual(result.pageErrors, []);
        result.entities = { txt: txt.id, csv: csv.id, json: json.id, publicPackage: publicPack.id, dictionaryPackage: dictPack.id, unlistedPackage: limited.id, privatePackage: privatePack.id };
        result.passed = true;
    } catch (error) {
        result.passed = false; result.failure = error.stack;
        await page.screenshot({ path: path.join(folder, 'failure.png'), fullPage: true }).catch(() => {});
        throw error;
    } finally {
        fs.writeFileSync(path.join(folder, 'result.json'), JSON.stringify(result, null, 2) + '\n');
        await browser.close();
    }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
